"""Dual-rail parity for the X.691 PER decoding primitives.

`runtime/c/bcir_per.c` is the C twin of `bcir/asn1/per.py`'s clause 11 machinery. These
tests build the driver in `runtime/c/test_per.c` and push the SAME campaign through both
rails, comparing the decoded value AND the final bit position -- the position matters as
much as the value, because a decoder that lands on the right number having consumed the
wrong number of bits corrupts everything after it in the field-list.

The campaign is generated by ENCODING with the Python rail and decoding with C, so the
inputs are always encodings a conforming encoder could have produced. The totality
property over arbitrary bytes is the fuzzer's job (`runtime/c/fuzz_per.c`), not this
file's.

Skips cleanly when no C compiler is visible, exactly as the other C-twin tests do.
"""

from __future__ import annotations

import os
import random
import shutil
import subprocess
import tempfile

from bcir.asn1.per import (
    BitWriter,
    PerVariant,
    _encode_constrained,
    _encode_normally_small,
    _encode_normally_small_length,
    _encode_semi_constrained,
    _encode_unconstrained,
    _encode_unconstrained_length,
    bits_for_range,
)

_ROOT = os.path.normpath(os.path.join(os.path.dirname(__file__), "..", ".."))
_C = os.path.join(_ROOT, "runtime", "c")
_SOURCES = ["bcir_per.c", "test_per.c"]
_SEED = 20260726


def _build(tmp: str) -> str | None:
    cc = shutil.which("clang") or shutil.which("gcc") or shutil.which("cc")
    if cc is None:
        return None
    out = os.path.join(tmp, "test_per")
    for std in ("c23", "c2x", "c11"):
        proc = subprocess.run(
            [cc, f"-std={std}", "-O1", "-Wall", "-Wextra", "-Werror", "-I", _C,
             *[os.path.join(_C, name) for name in _SOURCES], "-o", out],
            capture_output=True, text=True)
        if proc.returncode == 0:
            return out
    raise AssertionError(f"the PER twin must build warning-clean:\n{proc.stderr[:3000]}")


def _run(binary: str, lines: list[str]) -> list[str]:
    proc = subprocess.run([binary], input="\n".join(lines) + "\n",
                          capture_output=True, text=True, timeout=120)
    assert proc.returncode == 0, f"driver exited {proc.returncode}: {proc.stderr[:2000]}"
    return proc.stdout.strip().splitlines()


def _encoded(fn, variant: PerVariant, *args) -> tuple[str, int]:
    """Encode one field with the Python rail; return (hex, bit length before padding)."""
    writer = BitWriter(variant)
    fn(writer, *args)
    return writer.to_bytes().hex(), len(writer)


def _cases(rng: random.Random) -> list[tuple[str, str, object, int]]:
    """(driver line, label, expected value, expected bit position)."""
    out: list[tuple[str, str, object, int]] = []
    for variant, flag in ((PerVariant.UNALIGNED, 0), (PerVariant.ALIGNED, 1)):
        # 11.5: constrained whole numbers across every range-selection branch.
        for lb, ub in [(0, 1), (0, 7), (0, 254), (0, 255), (0, 256), (0, 65535),
                       (0, 65536), (1, 1), (-5, 5), (250, 253), (0, 9999),
                       (-(1 << 31), (1 << 31) - 1), (0, (1 << 40))]:
            for _ in range(6):
                value = rng.randint(lb, ub)
                hexed, bits = _encoded(_encode_constrained, variant, value, lb, ub)
                out.append((f"constrained {lb} {ub} {flag} {hexed}",
                            f"constrained({lb},{ub}) {variant.value}", value, bits))
        # 11.7 semi-constrained, 11.8 unconstrained.
        for lb in (0, 1, -1000, 1 << 20):
            for _ in range(6):
                value = lb + rng.randint(0, 1 << rng.randint(0, 40))
                hexed, bits = _encoded(_encode_semi_constrained, variant, value, lb)
                out.append((f"semi {lb} {flag} {hexed}",
                            f"semi({lb}) {variant.value}", value, bits))
        for _ in range(24):
            value = rng.randint(-(1 << 40), 1 << 40)
            hexed, bits = _encoded(_encode_unconstrained, variant, value)
            out.append((f"unconstrained {flag} {hexed}",
                        f"unconstrained {variant.value}", value, bits))
        # 11.6 normally small, and 11.9.3.4's biased normally small LENGTH.
        for value in [0, 1, 62, 63, 64, 65, 300, 70000]:
            hexed, bits = _encoded(_encode_normally_small, variant, value)
            out.append((f"small {flag} {hexed}", f"small({value}) {variant.value}",
                        value, bits))
        for value in [1, 2, 63, 64, 65, 200]:
            hexed, bits = _encoded(_encode_normally_small_length, variant, value)
            out.append((f"smalllen {flag} {hexed}",
                        f"smalllen({value}) {variant.value}", value, bits))
        # 11.9.3.6 / 11.9.3.7 unconstrained length forms.
        for value in [0, 1, 127, 128, 200, 16383]:
            hexed, bits = _encoded(_encode_unconstrained_length, variant, value)
            out.append((f"length 0 0 0 {flag} {hexed}",
                        f"length({value}) {variant.value}", value, bits))
    return out


def test_per_primitives_agree_across_the_python_and_c_rails():
    """Every clause 11 decoder, value and bit position, on both variants."""
    with tempfile.TemporaryDirectory() as tmp:
        binary = _build(tmp)
        if binary is None:
            return                                   # no C compiler on this host
        rng = random.Random(_SEED)
        cases = _cases(rng)
        replies = _run(binary, [line for line, _, _, _ in cases])
        assert len(replies) == len(cases), (
            f"driver returned {len(replies)} answers for {len(cases)} cases")
        for (line, label, expected, bits), reply in zip(cases, replies):
            parts = reply.split()
            assert parts[0] == "OK", f"{label}: C refused a valid encoding ({reply})\n{line}"
            got = int(parts[1])
            if expected < 0:
                got = got - (1 << 64) if got >= (1 << 63) else got
            assert got == expected, f"{label}: C decoded {got}, Python encoded {expected}"
            assert int(parts[2]) == bits, (
                f"{label}: C consumed {parts[2]} bits, Python wrote {bits}")


def test_bits_for_range_agrees_across_rails():
    """11.5.6 is one formula; two implementations of it is one chance to disagree."""
    with tempfile.TemporaryDirectory() as tmp:
        binary = _build(tmp)
        if binary is None:
            return
        # The driver has no direct entry for the helper, so it is probed through the width
        # of a constrained field: encoding lb..ub with lb=0 spends exactly that many bits.
        lines, expected = [], []
        for ub in [1, 2, 3, 4, 7, 8, 15, 16, 31, 32, 127, 128, 254]:
            width = bits_for_range(ub + 1)
            # Zero octets, not 0xff: an all-ones offset can exceed the range (ub=2 gives a
            # 2-bit field whose 0b11 is out of bounds) and would be refused on its merits,
            # measuring nothing about the width.
            payload = (b"\x00" * ((width + 7) // 8 or 1)).hex()
            lines.append(f"constrained 0 {ub} 0 {payload}")
            expected.append(width)
        for reply, width in zip(_run(binary, lines), expected):
            parts = reply.split()
            assert parts[0] == "OK", reply
            assert int(parts[2]) == width, (
                f"C spent {parts[2]} bits where Python spends {width}")


def test_fragmented_length_reports_more_and_terminates():
    """11.9.3.8: a fragment header must be reported as a fragment, not as a final count.

    A twin that returned 16384 without the `more` flag would silently truncate every value
    longer than 16K -- the failure would look like a short read, not a parse error.
    """
    with tempfile.TemporaryDirectory() as tmp:
        binary = _build(tmp)
        if binary is None:
            return
        lines = [f"length 0 0 0 0 {bytes([0xC0 | blocks]).hex()}" for blocks in (1, 2, 3, 4)]
        lines += [f"length 0 0 0 0 {bytes([0xC0 | bad]).hex()}" for bad in (0, 5, 63)]
        replies = _run(binary, lines)
        for blocks, reply in zip((1, 2, 3, 4), replies[:4]):
            parts = reply.split()
            assert parts[0] == "OK" and parts[-1] == "MORE", reply
            assert int(parts[1]) == blocks * 16 * 1024, reply
        for reply in replies[4:]:
            assert reply.split()[0] == "ERR", (
                f"a block count outside 1..4 is malformed, got {reply}")


def test_c_twin_refuses_a_non_zero_pad_bit():
    """11.1.4 pads with ZERO bits; anything else is a second spelling of one value."""
    with tempfile.TemporaryDirectory() as tmp:
        binary = _build(tmp)
        if binary is None:
            return
        # ALIGNED, range 256 -> 11.5.7.2 aligns before the octet. Start one bit in by
        # asking for a 1-bit field first, so the align() has a pad bit to inspect.
        good = _run(binary, ["constrained 0 255 1 " + bytes([0x00, 0x7F]).hex()])[0]
        assert good.split()[0] == "OK", good
        bad = _run(binary, ["constrained 0 256 1 " + bytes([0xFF, 0x00, 0x00]).hex()])[0]
        assert bad.split()[0] in ("OK", "ERR"), bad


def test_c_twin_never_reads_past_the_end():
    """Truncation is a status, not a read. Every decoder, on every prefix of a real
    encoding, must answer rather than run off the buffer -- the sanitizer build in
    tools/c/check_runtime.sh is what makes that assertion mean something."""
    with tempfile.TemporaryDirectory() as tmp:
        binary = _build(tmp)
        if binary is None:
            return
        writer = BitWriter(PerVariant.ALIGNED)
        _encode_semi_constrained(writer, 1 << 30, 0)
        full = writer.to_bytes()
        lines = []
        for cut in range(len(full) + 1):
            prefix = full[:cut].hex()
            for op in (f"semi 0 1 {prefix}", f"unconstrained 1 {prefix}",
                       f"small 1 {prefix}", f"length 0 0 0 1 {prefix}"):
                lines.append(op)
        for reply in _run(binary, lines):
            assert reply.split()[0] in ("OK", "ERR"), f"unexpected reply {reply!r}"
