// RUN: bcir-opt -bcir-classify-lanes -bcir-select-realization -bcir-batch -bcir-schedule -bcir-lower-to-llvm %s | FileCheck %s
//
// The widened corpus (real tiled matmul / scan / multi-claim histogram) on the
// AVX-512 profile (cool Theta, latency). GENERATED by the oracle -- regenerate
// with `python -m bcir.kbcir.differential --emit-corpus`. The law's min-plus
// argmin must recompute the oracle's per-claim score for every claim (parity).

bcir.module @matmul_tiled_avx512 {
  bcir.target.capability @cpu { triple = "x86_64-avx512", isa_features = ["avx2", "avx512f", "fma"], lane_widths = array<i64: 1, 8, 16>, cacheline = 64 : i32, gather_penalty = 32 : i32, affinity_domains = 8 : i32, thermal_density = 64 : i32, power_density = 64 : i32, mem_unit = 1 : i32, base_overhead = 4 : i32, per_op_heat = 1 : i32, elem_bytes = 4 : i32 }
  bcir.registry @RES {
    %r1000000 = bcir.resource @r1000000 { rid = 1000000 : i32, domain_kind = #bcir.domain<ram>, shape = array<i64: 128, 128>, layout = #bcir.layout<soa>, access = #bcir.access<flat> } : !bcir.resource
    %r1000001 = bcir.resource @r1000001 { rid = 1000001 : i32, domain_kind = #bcir.domain<ram>, shape = array<i64: 128, 128>, layout = #bcir.layout<soa>, access = #bcir.access<flat> } : !bcir.resource
    %r1000002 = bcir.resource @r1000002 { rid = 1000002 : i32, domain_kind = #bcir.domain<ram>, shape = array<i64: 128, 128>, layout = #bcir.layout<soa>, access = #bcir.access<flat> } : !bcir.resource
    %r1000003 = bcir.resource @r1000003 { rid = 1000003 : i32, domain_kind = #bcir.domain<ram>, shape = array<i64: 128, 128>, layout = #bcir.layout<soa>, access = #bcir.access<flat> } : !bcir.resource
    %r2000000 = bcir.resource @r2000000 { rid = 2000000 : i32, domain_kind = #bcir.domain<ram>, shape = array<i64: 128, 128>, layout = #bcir.layout<soa>, access = #bcir.access<flat> } : !bcir.resource
    %r2000001 = bcir.resource @r2000001 { rid = 2000001 : i32, domain_kind = #bcir.domain<ram>, shape = array<i64: 128, 128>, layout = #bcir.layout<soa>, access = #bcir.access<flat> } : !bcir.resource
    %r2000002 = bcir.resource @r2000002 { rid = 2000002 : i32, domain_kind = #bcir.domain<ram>, shape = array<i64: 128, 128>, layout = #bcir.layout<soa>, access = #bcir.access<flat> } : !bcir.resource
    %r2000003 = bcir.resource @r2000003 { rid = 2000003 : i32, domain_kind = #bcir.domain<ram>, shape = array<i64: 128, 128>, layout = #bcir.layout<soa>, access = #bcir.access<flat> } : !bcir.resource
    %r3000000 = bcir.resource @r3000000 { rid = 3000000 : i32, domain_kind = #bcir.domain<hbm>, shape = array<i64: 128, 128>, layout = #bcir.layout<soa>, access = #bcir.access<flat> } : !bcir.resource
    %r3000001 = bcir.resource @r3000001 { rid = 3000001 : i32, domain_kind = #bcir.domain<hbm>, shape = array<i64: 128, 128>, layout = #bcir.layout<soa>, access = #bcir.access<flat> } : !bcir.resource
    %r3000002 = bcir.resource @r3000002 { rid = 3000002 : i32, domain_kind = #bcir.domain<hbm>, shape = array<i64: 128, 128>, layout = #bcir.layout<soa>, access = #bcir.access<flat> } : !bcir.resource
    %r3000003 = bcir.resource @r3000003 { rid = 3000003 : i32, domain_kind = #bcir.domain<hbm>, shape = array<i64: 128, 128>, layout = #bcir.layout<soa>, access = #bcir.access<flat> } : !bcir.resource
  }
  bcir.kbcir.theta @theta { thermal = 0 : i32, power = 0 : i32, mem_pressure = 0 : i32, contention = 0 : i32 }
  bcir.kbcir.policy @perf { mode = #bcir.policy_mode<latency>, weights = array<i64: 2, 2, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1> }
  bcir.phase @p0 { id = 0 : i32, deps = [] }
  bcir.claim @c4000 attributes { claim_id = 4000 : i32, phase = @p0, op = "linalg.matmul", reads = [@r1000000, @r2000000], writes = [@r3000000], count = 16384 : i64, lane = #bcir.lane<t>, stride_class = #bcir.stride_class<tile>, stride_k = 1 : i32, domain = #bcir.domain<ram>, hazard = #bcir.hazard<unique>, verify = #bcir.verify<bounds>, bounds = #bcir.bounds<strict> } { %i = bcir.index_range 0 to 16384 step 1 }
  bcir.claim @c4001 attributes { claim_id = 4001 : i32, phase = @p0, op = "linalg.matmul", reads = [@r1000001, @r2000002, @r3000000], writes = [@r3000000], count = 16384 : i64, lane = #bcir.lane<t>, stride_class = #bcir.stride_class<tile>, stride_k = 1 : i32, domain = #bcir.domain<ram>, hazard = #bcir.hazard<unique>, verify = #bcir.verify<bounds>, bounds = #bcir.bounds<strict> } { %i = bcir.index_range 0 to 16384 step 1 }
  bcir.claim @c4002 attributes { claim_id = 4002 : i32, phase = @p0, op = "linalg.matmul", reads = [@r1000000, @r2000001], writes = [@r3000001], count = 16384 : i64, lane = #bcir.lane<t>, stride_class = #bcir.stride_class<tile>, stride_k = 1 : i32, domain = #bcir.domain<ram>, hazard = #bcir.hazard<unique>, verify = #bcir.verify<bounds>, bounds = #bcir.bounds<strict> } { %i = bcir.index_range 0 to 16384 step 1 }
  bcir.claim @c4003 attributes { claim_id = 4003 : i32, phase = @p0, op = "linalg.matmul", reads = [@r1000001, @r2000003, @r3000001], writes = [@r3000001], count = 16384 : i64, lane = #bcir.lane<t>, stride_class = #bcir.stride_class<tile>, stride_k = 1 : i32, domain = #bcir.domain<ram>, hazard = #bcir.hazard<unique>, verify = #bcir.verify<bounds>, bounds = #bcir.bounds<strict> } { %i = bcir.index_range 0 to 16384 step 1 }
  bcir.claim @c4004 attributes { claim_id = 4004 : i32, phase = @p0, op = "linalg.matmul", reads = [@r1000002, @r2000000], writes = [@r3000002], count = 16384 : i64, lane = #bcir.lane<t>, stride_class = #bcir.stride_class<tile>, stride_k = 1 : i32, domain = #bcir.domain<ram>, hazard = #bcir.hazard<unique>, verify = #bcir.verify<bounds>, bounds = #bcir.bounds<strict> } { %i = bcir.index_range 0 to 16384 step 1 }
  bcir.claim @c4005 attributes { claim_id = 4005 : i32, phase = @p0, op = "linalg.matmul", reads = [@r1000003, @r2000002, @r3000002], writes = [@r3000002], count = 16384 : i64, lane = #bcir.lane<t>, stride_class = #bcir.stride_class<tile>, stride_k = 1 : i32, domain = #bcir.domain<ram>, hazard = #bcir.hazard<unique>, verify = #bcir.verify<bounds>, bounds = #bcir.bounds<strict> } { %i = bcir.index_range 0 to 16384 step 1 }
  bcir.claim @c4006 attributes { claim_id = 4006 : i32, phase = @p0, op = "linalg.matmul", reads = [@r1000002, @r2000001], writes = [@r3000003], count = 16384 : i64, lane = #bcir.lane<t>, stride_class = #bcir.stride_class<tile>, stride_k = 1 : i32, domain = #bcir.domain<ram>, hazard = #bcir.hazard<unique>, verify = #bcir.verify<bounds>, bounds = #bcir.bounds<strict> } { %i = bcir.index_range 0 to 16384 step 1 }
  bcir.claim @c4007 attributes { claim_id = 4007 : i32, phase = @p0, op = "linalg.matmul", reads = [@r1000003, @r2000003, @r3000003], writes = [@r3000003], count = 16384 : i64, lane = #bcir.lane<t>, stride_class = #bcir.stride_class<tile>, stride_k = 1 : i32, domain = #bcir.domain<ram>, hazard = #bcir.hazard<unique>, verify = #bcir.verify<bounds>, bounds = #bcir.bounds<strict> } { %i = bcir.index_range 0 to 16384 step 1 }
  bcir.kbcir.plan @plan0 {
    %path_4000_tile = bcir.kbcir.path @path_4000_tile { claim = @c4000, realization = "t.tile", lane = #bcir.lane<t>, layout = #bcir.layout<soa>, cost = #bcir.costvec<compute = 2048, memory = 61440, fabric = 0, sync = 0, compile = 0, thermal = 2048, power = 2048, reliability = 0, security = 0, accuracy = 0, contention = 0, verification = 0> } : !bcir.path
    %sel_4000 = bcir.kbcir.select @c4000 from [@path_4000_tile] { policy = #bcir.policy_mode<latency>, semiring = #bcir.semiring<min_plus>, selected = @path_4000_tile, score = 126976 : i64 } : !bcir.path
    %path_4001_tile = bcir.kbcir.path @path_4001_tile { claim = @c4001, realization = "t.tile", lane = #bcir.lane<t>, layout = #bcir.layout<soa>, cost = #bcir.costvec<compute = 2048, memory = 61440, fabric = 0, sync = 0, compile = 0, thermal = 2048, power = 2048, reliability = 0, security = 0, accuracy = 0, contention = 0, verification = 0> } : !bcir.path
    %sel_4001 = bcir.kbcir.select @c4001 from [@path_4001_tile] { policy = #bcir.policy_mode<latency>, semiring = #bcir.semiring<min_plus>, selected = @path_4001_tile, score = 126976 : i64 } : !bcir.path
    %path_4002_tile = bcir.kbcir.path @path_4002_tile { claim = @c4002, realization = "t.tile", lane = #bcir.lane<t>, layout = #bcir.layout<soa>, cost = #bcir.costvec<compute = 2048, memory = 61440, fabric = 0, sync = 0, compile = 0, thermal = 2048, power = 2048, reliability = 0, security = 0, accuracy = 0, contention = 0, verification = 0> } : !bcir.path
    %sel_4002 = bcir.kbcir.select @c4002 from [@path_4002_tile] { policy = #bcir.policy_mode<latency>, semiring = #bcir.semiring<min_plus>, selected = @path_4002_tile, score = 126976 : i64 } : !bcir.path
    %path_4003_tile = bcir.kbcir.path @path_4003_tile { claim = @c4003, realization = "t.tile", lane = #bcir.lane<t>, layout = #bcir.layout<soa>, cost = #bcir.costvec<compute = 2048, memory = 61440, fabric = 0, sync = 0, compile = 0, thermal = 2048, power = 2048, reliability = 0, security = 0, accuracy = 0, contention = 0, verification = 0> } : !bcir.path
    %sel_4003 = bcir.kbcir.select @c4003 from [@path_4003_tile] { policy = #bcir.policy_mode<latency>, semiring = #bcir.semiring<min_plus>, selected = @path_4003_tile, score = 126976 : i64 } : !bcir.path
    %path_4004_tile = bcir.kbcir.path @path_4004_tile { claim = @c4004, realization = "t.tile", lane = #bcir.lane<t>, layout = #bcir.layout<soa>, cost = #bcir.costvec<compute = 2048, memory = 61440, fabric = 0, sync = 0, compile = 0, thermal = 2048, power = 2048, reliability = 0, security = 0, accuracy = 0, contention = 0, verification = 0> } : !bcir.path
    %sel_4004 = bcir.kbcir.select @c4004 from [@path_4004_tile] { policy = #bcir.policy_mode<latency>, semiring = #bcir.semiring<min_plus>, selected = @path_4004_tile, score = 126976 : i64 } : !bcir.path
    %path_4005_tile = bcir.kbcir.path @path_4005_tile { claim = @c4005, realization = "t.tile", lane = #bcir.lane<t>, layout = #bcir.layout<soa>, cost = #bcir.costvec<compute = 2048, memory = 61440, fabric = 0, sync = 0, compile = 0, thermal = 2048, power = 2048, reliability = 0, security = 0, accuracy = 0, contention = 0, verification = 0> } : !bcir.path
    %sel_4005 = bcir.kbcir.select @c4005 from [@path_4005_tile] { policy = #bcir.policy_mode<latency>, semiring = #bcir.semiring<min_plus>, selected = @path_4005_tile, score = 126976 : i64 } : !bcir.path
    %path_4006_tile = bcir.kbcir.path @path_4006_tile { claim = @c4006, realization = "t.tile", lane = #bcir.lane<t>, layout = #bcir.layout<soa>, cost = #bcir.costvec<compute = 2048, memory = 61440, fabric = 0, sync = 0, compile = 0, thermal = 2048, power = 2048, reliability = 0, security = 0, accuracy = 0, contention = 0, verification = 0> } : !bcir.path
    %sel_4006 = bcir.kbcir.select @c4006 from [@path_4006_tile] { policy = #bcir.policy_mode<latency>, semiring = #bcir.semiring<min_plus>, selected = @path_4006_tile, score = 126976 : i64 } : !bcir.path
    %path_4007_tile = bcir.kbcir.path @path_4007_tile { claim = @c4007, realization = "t.tile", lane = #bcir.lane<t>, layout = #bcir.layout<soa>, cost = #bcir.costvec<compute = 2048, memory = 61440, fabric = 0, sync = 0, compile = 0, thermal = 2048, power = 2048, reliability = 0, security = 0, accuracy = 0, contention = 0, verification = 0> } : !bcir.path
    %sel_4007 = bcir.kbcir.select @c4007 from [@path_4007_tile] { policy = #bcir.policy_mode<latency>, semiring = #bcir.semiring<min_plus>, selected = @path_4007_tile, score = 126976 : i64 } : !bcir.path
  }
  bcir.gem.lane_segment @seg_4000 { claim = @c4000, phase = @p0, lane = #bcir.lane<t>, stride_k = 1 : i32, width = 16 : i32, opcode = "linalg.matmul", reads = [@r1000000, @r2000000], writes = [@r3000000], fence_before = [], fence_after = [] }
  bcir.gem.lane_segment @seg_4001 { claim = @c4001, phase = @p0, lane = #bcir.lane<t>, stride_k = 1 : i32, width = 16 : i32, opcode = "linalg.matmul", reads = [@r1000001, @r2000002, @r3000000], writes = [@r3000000], fence_before = [], fence_after = [] }
  bcir.gem.lane_segment @seg_4002 { claim = @c4002, phase = @p0, lane = #bcir.lane<t>, stride_k = 1 : i32, width = 16 : i32, opcode = "linalg.matmul", reads = [@r1000000, @r2000001], writes = [@r3000001], fence_before = [], fence_after = [] }
  bcir.gem.lane_segment @seg_4003 { claim = @c4003, phase = @p0, lane = #bcir.lane<t>, stride_k = 1 : i32, width = 16 : i32, opcode = "linalg.matmul", reads = [@r1000001, @r2000003, @r3000001], writes = [@r3000001], fence_before = [], fence_after = [] }
  bcir.gem.lane_segment @seg_4004 { claim = @c4004, phase = @p0, lane = #bcir.lane<t>, stride_k = 1 : i32, width = 16 : i32, opcode = "linalg.matmul", reads = [@r1000002, @r2000000], writes = [@r3000002], fence_before = [], fence_after = [] }
  bcir.gem.lane_segment @seg_4005 { claim = @c4005, phase = @p0, lane = #bcir.lane<t>, stride_k = 1 : i32, width = 16 : i32, opcode = "linalg.matmul", reads = [@r1000003, @r2000002, @r3000002], writes = [@r3000002], fence_before = [], fence_after = [] }
  bcir.gem.lane_segment @seg_4006 { claim = @c4006, phase = @p0, lane = #bcir.lane<t>, stride_k = 1 : i32, width = 16 : i32, opcode = "linalg.matmul", reads = [@r1000002, @r2000001], writes = [@r3000003], fence_before = [], fence_after = [] }
  bcir.gem.lane_segment @seg_4007 { claim = @c4007, phase = @p0, lane = #bcir.lane<t>, stride_k = 1 : i32, width = 16 : i32, opcode = "linalg.matmul", reads = [@r1000003, @r2000003, @r3000003], writes = [@r3000003], fence_before = [], fence_after = [] }
}

// CHECK-LABEL: bcir.module @matmul_tiled_avx512
// CHECK-DAG: kbcir.classified_lane = "t"
// CHECK-DAG: kbcir.classified_lane = "t"
// CHECK-DAG: kbcir.classified_lane = "t"
// CHECK-DAG: kbcir.classified_lane = "t"
// CHECK-DAG: kbcir.classified_lane = "t"
// CHECK-DAG: kbcir.classified_lane = "t"
// CHECK-DAG: kbcir.classified_lane = "t"
// CHECK-DAG: kbcir.classified_lane = "t"
// CHECK-DAG: kbcir.computed_selected = @path_4000_tile
// CHECK-DAG: kbcir.computed_score = 126976
// CHECK-DAG: kbcir.computed_selected = @path_4001_tile
// CHECK-DAG: kbcir.computed_score = 126976
// CHECK-DAG: kbcir.computed_selected = @path_4002_tile
// CHECK-DAG: kbcir.computed_score = 126976
// CHECK-DAG: kbcir.computed_selected = @path_4003_tile
// CHECK-DAG: kbcir.computed_score = 126976
// CHECK-DAG: kbcir.computed_selected = @path_4004_tile
// CHECK-DAG: kbcir.computed_score = 126976
// CHECK-DAG: kbcir.computed_selected = @path_4005_tile
// CHECK-DAG: kbcir.computed_score = 126976
// CHECK-DAG: kbcir.computed_selected = @path_4006_tile
// CHECK-DAG: kbcir.computed_score = 126976
// CHECK-DAG: kbcir.computed_selected = @path_4007_tile
// CHECK-DAG: kbcir.computed_score = 126976
// CHECK-DAG: kbcir.lowered = true

bcir.module @scan_avx512 {
  bcir.target.capability @cpu { triple = "x86_64-avx512", isa_features = ["avx2", "avx512f", "fma"], lane_widths = array<i64: 1, 8, 16>, cacheline = 64 : i32, gather_penalty = 32 : i32, affinity_domains = 8 : i32, thermal_density = 64 : i32, power_density = 64 : i32, mem_unit = 1 : i32, base_overhead = 4 : i32, per_op_heat = 1 : i32, elem_bytes = 4 : i32 }
  bcir.registry @RES {
    %r8000 = bcir.resource @r8000 { rid = 8000 : i32, domain_kind = #bcir.domain<ram>, shape = array<i64: 4096>, layout = #bcir.layout<soa>, access = #bcir.access<flat> } : !bcir.resource
    %r8001 = bcir.resource @r8001 { rid = 8001 : i32, domain_kind = #bcir.domain<ram>, shape = array<i64: 4096>, layout = #bcir.layout<soa>, access = #bcir.access<flat> } : !bcir.resource
    %r8100 = bcir.resource @r8100 { rid = 8100 : i32, domain_kind = #bcir.domain<ram>, shape = array<i64: 4096>, layout = #bcir.layout<soa>, access = #bcir.access<flat> } : !bcir.resource
    %r8101 = bcir.resource @r8101 { rid = 8101 : i32, domain_kind = #bcir.domain<ram>, shape = array<i64: 4096>, layout = #bcir.layout<soa>, access = #bcir.access<flat> } : !bcir.resource
    %r8102 = bcir.resource @r8102 { rid = 8102 : i32, domain_kind = #bcir.domain<ram>, shape = array<i64: 4096>, layout = #bcir.layout<soa>, access = #bcir.access<flat> } : !bcir.resource
    %r8103 = bcir.resource @r8103 { rid = 8103 : i32, domain_kind = #bcir.domain<ram>, shape = array<i64: 4096>, layout = #bcir.layout<soa>, access = #bcir.access<flat> } : !bcir.resource
    %r8201 = bcir.resource @r8201 { rid = 8201 : i32, domain_kind = #bcir.domain<ram>, shape = array<i64: 4096>, layout = #bcir.layout<soa>, access = #bcir.access<flat> } : !bcir.resource
    %r8202 = bcir.resource @r8202 { rid = 8202 : i32, domain_kind = #bcir.domain<ram>, shape = array<i64: 4096>, layout = #bcir.layout<soa>, access = #bcir.access<flat> } : !bcir.resource
    %r8203 = bcir.resource @r8203 { rid = 8203 : i32, domain_kind = #bcir.domain<ram>, shape = array<i64: 4096>, layout = #bcir.layout<soa>, access = #bcir.access<flat> } : !bcir.resource
  }
  bcir.kbcir.theta @theta { thermal = 0 : i32, power = 0 : i32, mem_pressure = 0 : i32, contention = 0 : i32 }
  bcir.kbcir.policy @perf { mode = #bcir.policy_mode<latency>, weights = array<i64: 2, 2, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1> }
  bcir.phase @p0 { id = 0 : i32, deps = [] }
  bcir.claim @c8300 attributes { claim_id = 8300 : i32, phase = @p0, op = "vector.add", reads = [@r8000, @r8001], writes = [@r8100], count = 4096 : i64, lane = #bcir.lane<u>, stride_class = #bcir.stride_class<unit>, stride_k = 1 : i32, domain = #bcir.domain<ram>, hazard = #bcir.hazard<unique>, verify = #bcir.verify<bounds>, bounds = #bcir.bounds<strict> } { %i = bcir.index_range 0 to 4096 step 1 }
  bcir.claim @c8301 attributes { claim_id = 8301 : i32, phase = @p0, op = "vector.add", reads = [@r8100, @r8201], writes = [@r8101], count = 4096 : i64, lane = #bcir.lane<u>, stride_class = #bcir.stride_class<unit>, stride_k = 1 : i32, domain = #bcir.domain<ram>, hazard = #bcir.hazard<unique>, verify = #bcir.verify<bounds>, bounds = #bcir.bounds<strict> } { %i = bcir.index_range 0 to 4096 step 1 }
  bcir.claim @c8302 attributes { claim_id = 8302 : i32, phase = @p0, op = "vector.add", reads = [@r8101, @r8202], writes = [@r8102], count = 4096 : i64, lane = #bcir.lane<u>, stride_class = #bcir.stride_class<unit>, stride_k = 1 : i32, domain = #bcir.domain<ram>, hazard = #bcir.hazard<unique>, verify = #bcir.verify<bounds>, bounds = #bcir.bounds<strict> } { %i = bcir.index_range 0 to 4096 step 1 }
  bcir.claim @c8303 attributes { claim_id = 8303 : i32, phase = @p0, op = "vector.add", reads = [@r8102, @r8203], writes = [@r8103], count = 4096 : i64, lane = #bcir.lane<u>, stride_class = #bcir.stride_class<unit>, stride_k = 1 : i32, domain = #bcir.domain<ram>, hazard = #bcir.hazard<unique>, verify = #bcir.verify<bounds>, bounds = #bcir.bounds<strict> } { %i = bcir.index_range 0 to 4096 step 1 }
  bcir.kbcir.plan @plan0 {
    %path_8300_scalar = bcir.kbcir.path @path_8300_scalar { claim = @c8300, realization = "u.scalar", lane = #bcir.lane<u>, layout = #bcir.layout<soa>, cost = #bcir.costvec<compute = 4096, memory = 61440, fabric = 0, sync = 0, compile = 0, thermal = 4160, power = 4160, reliability = 0, security = 0, accuracy = 0, contention = 0, verification = 0> } : !bcir.path
    %path_8300_vec8 = bcir.kbcir.path @path_8300_vec8 { claim = @c8300, realization = "u.vec8", lane = #bcir.lane<u>, layout = #bcir.layout<soa>, cost = #bcir.costvec<compute = 512, memory = 18432, fabric = 0, sync = 0, compile = 0, thermal = 1024, power = 1024, reliability = 0, security = 0, accuracy = 0, contention = 0, verification = 0> } : !bcir.path
    %path_8300_vec16 = bcir.kbcir.path @path_8300_vec16 { claim = @c8300, realization = "u.vec16", lane = #bcir.lane<u>, layout = #bcir.layout<soa>, cost = #bcir.costvec<compute = 256, memory = 15360, fabric = 0, sync = 0, compile = 0, thermal = 1280, power = 1280, reliability = 0, security = 0, accuracy = 0, contention = 0, verification = 0> } : !bcir.path
    %sel_8300 = bcir.kbcir.select @c8300 from [@path_8300_scalar, @path_8300_vec8, @path_8300_vec16] { policy = #bcir.policy_mode<latency>, semiring = #bcir.semiring<min_plus>, selected = @path_8300_vec16, score = 31232 : i64 } : !bcir.path
    %path_8301_scalar = bcir.kbcir.path @path_8301_scalar { claim = @c8301, realization = "u.scalar", lane = #bcir.lane<u>, layout = #bcir.layout<soa>, cost = #bcir.costvec<compute = 4096, memory = 46080, fabric = 0, sync = 0, compile = 0, thermal = 4160, power = 4160, reliability = 0, security = 0, accuracy = 0, contention = 0, verification = 0> } : !bcir.path
    %path_8301_vec8 = bcir.kbcir.path @path_8301_vec8 { claim = @c8301, realization = "u.vec8", lane = #bcir.lane<u>, layout = #bcir.layout<soa>, cost = #bcir.costvec<compute = 512, memory = 13824, fabric = 0, sync = 0, compile = 0, thermal = 1024, power = 1024, reliability = 0, security = 0, accuracy = 0, contention = 0, verification = 0> } : !bcir.path
    %path_8301_vec16 = bcir.kbcir.path @path_8301_vec16 { claim = @c8301, realization = "u.vec16", lane = #bcir.lane<u>, layout = #bcir.layout<soa>, cost = #bcir.costvec<compute = 256, memory = 11520, fabric = 0, sync = 0, compile = 0, thermal = 1280, power = 1280, reliability = 0, security = 0, accuracy = 0, contention = 0, verification = 0> } : !bcir.path
    %sel_8301 = bcir.kbcir.select @c8301 from [@path_8301_scalar, @path_8301_vec8, @path_8301_vec16] { policy = #bcir.policy_mode<latency>, semiring = #bcir.semiring<min_plus>, selected = @path_8301_vec16, score = 23552 : i64 } : !bcir.path
    %path_8302_scalar = bcir.kbcir.path @path_8302_scalar { claim = @c8302, realization = "u.scalar", lane = #bcir.lane<u>, layout = #bcir.layout<soa>, cost = #bcir.costvec<compute = 4096, memory = 46080, fabric = 0, sync = 0, compile = 0, thermal = 4160, power = 4160, reliability = 0, security = 0, accuracy = 0, contention = 0, verification = 0> } : !bcir.path
    %path_8302_vec8 = bcir.kbcir.path @path_8302_vec8 { claim = @c8302, realization = "u.vec8", lane = #bcir.lane<u>, layout = #bcir.layout<soa>, cost = #bcir.costvec<compute = 512, memory = 13824, fabric = 0, sync = 0, compile = 0, thermal = 1024, power = 1024, reliability = 0, security = 0, accuracy = 0, contention = 0, verification = 0> } : !bcir.path
    %path_8302_vec16 = bcir.kbcir.path @path_8302_vec16 { claim = @c8302, realization = "u.vec16", lane = #bcir.lane<u>, layout = #bcir.layout<soa>, cost = #bcir.costvec<compute = 256, memory = 11520, fabric = 0, sync = 0, compile = 0, thermal = 1280, power = 1280, reliability = 0, security = 0, accuracy = 0, contention = 0, verification = 0> } : !bcir.path
    %sel_8302 = bcir.kbcir.select @c8302 from [@path_8302_scalar, @path_8302_vec8, @path_8302_vec16] { policy = #bcir.policy_mode<latency>, semiring = #bcir.semiring<min_plus>, selected = @path_8302_vec16, score = 23552 : i64 } : !bcir.path
    %path_8303_scalar = bcir.kbcir.path @path_8303_scalar { claim = @c8303, realization = "u.scalar", lane = #bcir.lane<u>, layout = #bcir.layout<soa>, cost = #bcir.costvec<compute = 4096, memory = 46080, fabric = 0, sync = 0, compile = 0, thermal = 4160, power = 4160, reliability = 0, security = 0, accuracy = 0, contention = 0, verification = 0> } : !bcir.path
    %path_8303_vec8 = bcir.kbcir.path @path_8303_vec8 { claim = @c8303, realization = "u.vec8", lane = #bcir.lane<u>, layout = #bcir.layout<soa>, cost = #bcir.costvec<compute = 512, memory = 13824, fabric = 0, sync = 0, compile = 0, thermal = 1024, power = 1024, reliability = 0, security = 0, accuracy = 0, contention = 0, verification = 0> } : !bcir.path
    %path_8303_vec16 = bcir.kbcir.path @path_8303_vec16 { claim = @c8303, realization = "u.vec16", lane = #bcir.lane<u>, layout = #bcir.layout<soa>, cost = #bcir.costvec<compute = 256, memory = 11520, fabric = 0, sync = 0, compile = 0, thermal = 1280, power = 1280, reliability = 0, security = 0, accuracy = 0, contention = 0, verification = 0> } : !bcir.path
    %sel_8303 = bcir.kbcir.select @c8303 from [@path_8303_scalar, @path_8303_vec8, @path_8303_vec16] { policy = #bcir.policy_mode<latency>, semiring = #bcir.semiring<min_plus>, selected = @path_8303_vec16, score = 23552 : i64 } : !bcir.path
  }
  bcir.gem.lane_segment @seg_8300 { claim = @c8300, phase = @p0, lane = #bcir.lane<u>, stride_k = 1 : i32, width = 16 : i32, opcode = "vector.add", reads = [@r8000, @r8001], writes = [@r8100], fence_before = [], fence_after = [] }
  bcir.gem.lane_segment @seg_8301 { claim = @c8301, phase = @p0, lane = #bcir.lane<u>, stride_k = 1 : i32, width = 16 : i32, opcode = "vector.add", reads = [@r8100, @r8201], writes = [@r8101], fence_before = [], fence_after = [] }
  bcir.gem.lane_segment @seg_8302 { claim = @c8302, phase = @p0, lane = #bcir.lane<u>, stride_k = 1 : i32, width = 16 : i32, opcode = "vector.add", reads = [@r8101, @r8202], writes = [@r8102], fence_before = [], fence_after = [] }
  bcir.gem.lane_segment @seg_8303 { claim = @c8303, phase = @p0, lane = #bcir.lane<u>, stride_k = 1 : i32, width = 16 : i32, opcode = "vector.add", reads = [@r8102, @r8203], writes = [@r8103], fence_before = [], fence_after = [] }
}

// CHECK-LABEL: bcir.module @scan_avx512
// CHECK-DAG: kbcir.classified_lane = "u"
// CHECK-DAG: kbcir.classified_lane = "u"
// CHECK-DAG: kbcir.classified_lane = "u"
// CHECK-DAG: kbcir.classified_lane = "u"
// CHECK-DAG: kbcir.computed_selected = @path_8300_vec16
// CHECK-DAG: kbcir.computed_score = 31232
// CHECK-DAG: kbcir.computed_selected = @path_8301_vec16
// CHECK-DAG: kbcir.computed_score = 23552
// CHECK-DAG: kbcir.computed_selected = @path_8302_vec16
// CHECK-DAG: kbcir.computed_score = 23552
// CHECK-DAG: kbcir.computed_selected = @path_8303_vec16
// CHECK-DAG: kbcir.computed_score = 23552
// CHECK-DAG: kbcir.lowered = true

bcir.module @multi_histogram_avx512 {
  bcir.target.capability @cpu { triple = "x86_64-avx512", isa_features = ["avx2", "avx512f", "fma"], lane_widths = array<i64: 1, 8, 16>, cacheline = 64 : i32, gather_penalty = 32 : i32, affinity_domains = 8 : i32, thermal_density = 64 : i32, power_density = 64 : i32, mem_unit = 1 : i32, base_overhead = 4 : i32, per_op_heat = 1 : i32, elem_bytes = 4 : i32 }
  bcir.registry @RES {
    %r9000 = bcir.resource @r9000 { rid = 9000 : i32, domain_kind = #bcir.domain<ram>, shape = array<i64: 1024>, layout = #bcir.layout<soa>, access = #bcir.access<flat> } : !bcir.resource
    %r9100 = bcir.resource @r9100 { rid = 9100 : i32, domain_kind = #bcir.domain<ram>, shape = array<i64: 1024>, layout = #bcir.layout<soa>, access = #bcir.access<flat> } : !bcir.resource
    %r9101 = bcir.resource @r9101 { rid = 9101 : i32, domain_kind = #bcir.domain<ram>, shape = array<i64: 1024>, layout = #bcir.layout<soa>, access = #bcir.access<flat> } : !bcir.resource
    %r9102 = bcir.resource @r9102 { rid = 9102 : i32, domain_kind = #bcir.domain<ram>, shape = array<i64: 1024>, layout = #bcir.layout<soa>, access = #bcir.access<flat> } : !bcir.resource
    %r9200 = bcir.resource @r9200 { rid = 9200 : i32, domain_kind = #bcir.domain<ram>, shape = array<i64: 1024>, layout = #bcir.layout<soa>, access = #bcir.access<flat> } : !bcir.resource
  }
  bcir.kbcir.theta @theta { thermal = 0 : i32, power = 0 : i32, mem_pressure = 0 : i32, contention = 0 : i32 }
  bcir.kbcir.policy @perf { mode = #bcir.policy_mode<latency>, weights = array<i64: 2, 2, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1> }
  bcir.phase @p0 { id = 0 : i32, deps = [] }
  bcir.phase @p1 { id = 1 : i32, deps = [@p0] }
  bcir.claim @c9300 attributes { claim_id = 9300 : i32, phase = @p0, op = "histogram.scatter", reads = [@r9000], writes = [@r9100], count = 1024 : i64, lane = #bcir.lane<ggg>, stride_class = #bcir.stride_class<random>, stride_k = 1 : i32, domain = #bcir.domain<ram>, hazard = #bcir.hazard<unique>, verify = #bcir.verify<bounds>, bounds = #bcir.bounds<strict> } { %i = bcir.index_range 0 to 1024 step 1 }
  bcir.claim @c9301 attributes { claim_id = 9301 : i32, phase = @p0, op = "histogram.scatter", reads = [@r9000], writes = [@r9101], count = 1024 : i64, lane = #bcir.lane<ggg>, stride_class = #bcir.stride_class<random>, stride_k = 1 : i32, domain = #bcir.domain<ram>, hazard = #bcir.hazard<unique>, verify = #bcir.verify<bounds>, bounds = #bcir.bounds<strict> } { %i = bcir.index_range 0 to 1024 step 1 }
  bcir.claim @c9302 attributes { claim_id = 9302 : i32, phase = @p0, op = "histogram.scatter", reads = [@r9000], writes = [@r9102], count = 1024 : i64, lane = #bcir.lane<ggg>, stride_class = #bcir.stride_class<random>, stride_k = 1 : i32, domain = #bcir.domain<ram>, hazard = #bcir.hazard<unique>, verify = #bcir.verify<bounds>, bounds = #bcir.bounds<strict> } { %i = bcir.index_range 0 to 1024 step 1 }
  bcir.claim @c9400 attributes { claim_id = 9400 : i32, phase = @p1, op = "reduce.add", reads = [@r9100, @r9101, @r9102], writes = [@r9200], count = 1024 : i64, lane = #bcir.lane<u>, stride_class = #bcir.stride_class<unit>, stride_k = 1 : i32, domain = #bcir.domain<ram>, hazard = #bcir.hazard<unique>, verify = #bcir.verify<bounds>, bounds = #bcir.bounds<strict> } { %i = bcir.index_range 0 to 1024 step 1 }
  bcir.kbcir.plan @plan0 {
    %path_9300_gather = bcir.kbcir.path @path_9300_gather { claim = @c9300, realization = "ggg.gather", lane = #bcir.lane<ggg>, layout = #bcir.layout<soa>, cost = #bcir.costvec<compute = 0, memory = 264192, fabric = 0, sync = 0, compile = 0, thermal = 1088, power = 1088, reliability = 0, security = 0, accuracy = 0, contention = 0, verification = 0> } : !bcir.path
    %sel_9300 = bcir.kbcir.select @c9300 from [@path_9300_gather] { policy = #bcir.policy_mode<latency>, semiring = #bcir.semiring<min_plus>, selected = @path_9300_gather, score = 528384 : i64 } : !bcir.path
    %path_9301_gather = bcir.kbcir.path @path_9301_gather { claim = @c9301, realization = "ggg.gather", lane = #bcir.lane<ggg>, layout = #bcir.layout<soa>, cost = #bcir.costvec<compute = 0, memory = 264192, fabric = 0, sync = 0, compile = 0, thermal = 1088, power = 1088, reliability = 0, security = 0, accuracy = 0, contention = 0, verification = 0> } : !bcir.path
    %sel_9301 = bcir.kbcir.select @c9301 from [@path_9301_gather] { policy = #bcir.policy_mode<latency>, semiring = #bcir.semiring<min_plus>, selected = @path_9301_gather, score = 528384 : i64 } : !bcir.path
    %path_9302_gather = bcir.kbcir.path @path_9302_gather { claim = @c9302, realization = "ggg.gather", lane = #bcir.lane<ggg>, layout = #bcir.layout<soa>, cost = #bcir.costvec<compute = 0, memory = 264192, fabric = 0, sync = 0, compile = 0, thermal = 1088, power = 1088, reliability = 0, security = 0, accuracy = 0, contention = 0, verification = 0> } : !bcir.path
    %sel_9302 = bcir.kbcir.select @c9302 from [@path_9302_gather] { policy = #bcir.policy_mode<latency>, semiring = #bcir.semiring<min_plus>, selected = @path_9302_gather, score = 528384 : i64 } : !bcir.path
    %path_9400_scalar = bcir.kbcir.path @path_9400_scalar { claim = @c9400, realization = "u.scalar", lane = #bcir.lane<u>, layout = #bcir.layout<soa>, cost = #bcir.costvec<compute = 1024, memory = 20480, fabric = 0, sync = 0, compile = 0, thermal = 1088, power = 1088, reliability = 0, security = 0, accuracy = 0, contention = 0, verification = 0> } : !bcir.path
    %path_9400_vec8 = bcir.kbcir.path @path_9400_vec8 { claim = @c9400, realization = "u.vec8", lane = #bcir.lane<u>, layout = #bcir.layout<soa>, cost = #bcir.costvec<compute = 128, memory = 6144, fabric = 0, sync = 0, compile = 0, thermal = 640, power = 640, reliability = 0, security = 0, accuracy = 0, contention = 0, verification = 0> } : !bcir.path
    %path_9400_vec16 = bcir.kbcir.path @path_9400_vec16 { claim = @c9400, realization = "u.vec16", lane = #bcir.lane<u>, layout = #bcir.layout<soa>, cost = #bcir.costvec<compute = 64, memory = 5120, fabric = 0, sync = 0, compile = 0, thermal = 1088, power = 1088, reliability = 0, security = 0, accuracy = 0, contention = 0, verification = 0> } : !bcir.path
    %sel_9400 = bcir.kbcir.select @c9400 from [@path_9400_scalar, @path_9400_vec8, @path_9400_vec16] { policy = #bcir.policy_mode<latency>, semiring = #bcir.semiring<min_plus>, selected = @path_9400_vec16, score = 10368 : i64 } : !bcir.path
  }
  bcir.gem.lane_segment @seg_9300 { claim = @c9300, phase = @p0, lane = #bcir.lane<ggg>, stride_k = 1 : i32, width = 1 : i32, opcode = "histogram.scatter", reads = [@r9000], writes = [@r9100], fence_before = [], fence_after = [] }
  bcir.gem.lane_segment @seg_9301 { claim = @c9301, phase = @p0, lane = #bcir.lane<ggg>, stride_k = 1 : i32, width = 1 : i32, opcode = "histogram.scatter", reads = [@r9000], writes = [@r9101], fence_before = [], fence_after = [] }
  bcir.gem.lane_segment @seg_9302 { claim = @c9302, phase = @p0, lane = #bcir.lane<ggg>, stride_k = 1 : i32, width = 1 : i32, opcode = "histogram.scatter", reads = [@r9000], writes = [@r9102], fence_before = [], fence_after = [] }
  bcir.gem.lane_segment @seg_9400 { claim = @c9400, phase = @p1, lane = #bcir.lane<u>, stride_k = 1 : i32, width = 16 : i32, opcode = "reduce.add", reads = [@r9100, @r9101, @r9102], writes = [@r9200], fence_before = [], fence_after = [] }
}

// CHECK-LABEL: bcir.module @multi_histogram_avx512
// CHECK-DAG: kbcir.classified_lane = "ggg"
// CHECK-DAG: kbcir.classified_lane = "ggg"
// CHECK-DAG: kbcir.classified_lane = "ggg"
// CHECK-DAG: kbcir.classified_lane = "u"
// CHECK-DAG: kbcir.computed_selected = @path_9300_gather
// CHECK-DAG: kbcir.computed_score = 528384
// CHECK-DAG: kbcir.computed_selected = @path_9301_gather
// CHECK-DAG: kbcir.computed_score = 528384
// CHECK-DAG: kbcir.computed_selected = @path_9302_gather
// CHECK-DAG: kbcir.computed_score = 528384
// CHECK-DAG: kbcir.computed_selected = @path_9400_vec16
// CHECK-DAG: kbcir.computed_score = 10368
// CHECK-DAG: kbcir.lowered = true

