// RUN: bcir-opt -bcir-verify -verify-diagnostics -split-input-file %s
//
// GENERATED by `python -m bcir.verify.structural_corpus --emit` -- do not edit by hand.
// The shared structural-law corpus (S0-6): every law-rail case of bcir/verify/structural_corpus.py,
// rendered with its expected diagnostic. The oracle runner over the SAME cases is
// bcir/tests/test_structural_corpus.py (the quick tier), which also refuses drift between this
// file and the corpus (`--check`). Widths, alignments, shapes and strides; phase identity; the
// isolated-domain rule; the target descriptor; the address width under a declared target; the
// R13 manifest, portfolio and calibration records; the M5 descriptors; the convolution wire
// domain; the MAP/ROP derived domain contract -- one corpus, two runners, every mismatch a finding.

// -----

// resource.legal [legal]
bcir.module @m {
  bcir.registry @RES {
    bcir.resource @r1 { rid = 1 : i32, domain_kind = #bcir.domain<ram>, shape = array<i64: 8>, layout = #bcir.layout<soa>, align = 64 : i32 }
  }
  bcir.phase @p0 { id = 0 : i32, deps = [] }
  bcir.claim @c1 attributes { claim_id = 1 : i32, phase = @p0, op = "vector.add", reads = [@r1], writes = [@r1], count = 8 : i64, lane = #bcir.lane<u>, stride_class = #bcir.stride_class<unit>, stride_k = 1 : i32, offset = 0 : i64, domain = #bcir.domain<ram>, hazard = #bcir.hazard<unique>, verify = #bcir.verify<bounds>, bounds = #bcir.bounds<strict> } { %i = bcir.index_range 0 to 8 step 1 }
}

// -----

// resource.shape.unknown [legal] -- an empty shape is an UNKNOWN extent on both rails: R7 cannot check it, R1 admits it
bcir.module @m {
  bcir.registry @RES {
    bcir.resource @r1 { rid = 1 : i32, domain_kind = #bcir.domain<ram>, shape = array<i64>, layout = #bcir.layout<soa>, align = 64 : i32 }
  }
  bcir.phase @p0 { id = 0 : i32, deps = [] }
  bcir.claim @c1 attributes { claim_id = 1 : i32, phase = @p0, op = "vector.add", reads = [@r1], writes = [@r1], count = 8 : i64, lane = #bcir.lane<u>, stride_class = #bcir.stride_class<unit>, stride_k = 1 : i32, offset = 0 : i64, domain = #bcir.domain<ram>, hazard = #bcir.hazard<unique>, verify = #bcir.verify<bounds>, bounds = #bcir.bounds<strict> } { %i = bcir.index_range 0 to 8 step 1 }
}

// -----

// resource.shape.zero [R1]
bcir.module @m {
  bcir.registry @RES {
    bcir.resource @r1 { rid = 1 : i32, domain_kind = #bcir.domain<ram>, shape = array<i64: 8>, layout = #bcir.layout<soa>, align = 64 : i32 }
    // expected-error @+1 {{shape extents must be positive (got 0)}}
    bcir.resource @r2 { rid = 2 : i32, domain_kind = #bcir.domain<ram>, shape = array<i64: 0>, layout = #bcir.layout<soa>, align = 64 : i32 }
  }
  bcir.phase @p0 { id = 0 : i32, deps = [] }
  bcir.claim @c1 attributes { claim_id = 1 : i32, phase = @p0, op = "vector.add", reads = [@r1], writes = [@r1], count = 8 : i64, lane = #bcir.lane<u>, stride_class = #bcir.stride_class<unit>, stride_k = 1 : i32, offset = 0 : i64, domain = #bcir.domain<ram>, hazard = #bcir.hazard<unique>, verify = #bcir.verify<bounds>, bounds = #bcir.bounds<strict> } { %i = bcir.index_range 0 to 8 step 1 }
}

// -----

// resource.shape.negative [R1]
bcir.module @m {
  bcir.registry @RES {
    bcir.resource @r1 { rid = 1 : i32, domain_kind = #bcir.domain<ram>, shape = array<i64: 8>, layout = #bcir.layout<soa>, align = 64 : i32 }
    // expected-error @+1 {{shape extents must be positive (got -4)}}
    bcir.resource @r2 { rid = 2 : i32, domain_kind = #bcir.domain<ram>, shape = array<i64: -4>, layout = #bcir.layout<soa>, align = 64 : i32 }
  }
  bcir.phase @p0 { id = 0 : i32, deps = [] }
  bcir.claim @c1 attributes { claim_id = 1 : i32, phase = @p0, op = "vector.add", reads = [@r1], writes = [@r1], count = 8 : i64, lane = #bcir.lane<u>, stride_class = #bcir.stride_class<unit>, stride_k = 1 : i32, offset = 0 : i64, domain = #bcir.domain<ram>, hazard = #bcir.hazard<unique>, verify = #bcir.verify<bounds>, bounds = #bcir.bounds<strict> } { %i = bcir.index_range 0 to 8 step 1 }
}

// -----

// resource.shape.overflow [R1]
bcir.module @m {
  bcir.registry @RES {
    bcir.resource @r1 { rid = 1 : i32, domain_kind = #bcir.domain<ram>, shape = array<i64: 8>, layout = #bcir.layout<soa>, align = 64 : i32 }
    // expected-error @+1 {{shape element count exceeds signed 64-bit range}}
    bcir.resource @r2 { rid = 2 : i32, domain_kind = #bcir.domain<ram>, shape = array<i64: 4294967296, 4294967296>, layout = #bcir.layout<soa>, align = 64 : i32 }
  }
  bcir.phase @p0 { id = 0 : i32, deps = [] }
  bcir.claim @c1 attributes { claim_id = 1 : i32, phase = @p0, op = "vector.add", reads = [@r1], writes = [@r1], count = 8 : i64, lane = #bcir.lane<u>, stride_class = #bcir.stride_class<unit>, stride_k = 1 : i32, offset = 0 : i64, domain = #bcir.domain<ram>, hazard = #bcir.hazard<unique>, verify = #bcir.verify<bounds>, bounds = #bcir.bounds<strict> } { %i = bcir.index_range 0 to 8 step 1 }
}

// -----

// resource.align.not_pow2 [R1]
bcir.module @m {
  bcir.registry @RES {
    // expected-error @+1 {{align must be a positive power of two (got 3)}}
    bcir.resource @r1 { rid = 1 : i32, domain_kind = #bcir.domain<ram>, shape = array<i64: 8>, layout = #bcir.layout<soa>, align = 3 : i32 }
  }
  bcir.phase @p0 { id = 0 : i32, deps = [] }
  bcir.claim @c1 attributes { claim_id = 1 : i32, phase = @p0, op = "vector.add", reads = [@r1], writes = [@r1], count = 8 : i64, lane = #bcir.lane<u>, stride_class = #bcir.stride_class<unit>, stride_k = 1 : i32, offset = 0 : i64, domain = #bcir.domain<ram>, hazard = #bcir.hazard<unique>, verify = #bcir.verify<bounds>, bounds = #bcir.bounds<strict> } { %i = bcir.index_range 0 to 8 step 1 }
}

// -----

// resource.align.zero [R1]
bcir.module @m {
  bcir.registry @RES {
    // expected-error @+1 {{align must be a positive power of two (got 0)}}
    bcir.resource @r1 { rid = 1 : i32, domain_kind = #bcir.domain<ram>, shape = array<i64: 8>, layout = #bcir.layout<soa>, align = 0 : i32 }
  }
  bcir.phase @p0 { id = 0 : i32, deps = [] }
  bcir.claim @c1 attributes { claim_id = 1 : i32, phase = @p0, op = "vector.add", reads = [@r1], writes = [@r1], count = 8 : i64, lane = #bcir.lane<u>, stride_class = #bcir.stride_class<unit>, stride_k = 1 : i32, offset = 0 : i64, domain = #bcir.domain<ram>, hazard = #bcir.hazard<unique>, verify = #bcir.verify<bounds>, bounds = #bcir.bounds<strict> } { %i = bcir.index_range 0 to 8 step 1 }
}

// -----

// claim.count.zero [legal]
bcir.module @m {
  bcir.registry @RES {
    bcir.resource @r1 { rid = 1 : i32, domain_kind = #bcir.domain<ram>, shape = array<i64: 8>, layout = #bcir.layout<soa>, align = 64 : i32 }
  }
  bcir.phase @p0 { id = 0 : i32, deps = [] }
  bcir.claim @c1 attributes { claim_id = 1 : i32, phase = @p0, op = "vector.add", reads = [@r1], writes = [@r1], count = 0 : i64, lane = #bcir.lane<u>, stride_class = #bcir.stride_class<unit>, stride_k = 1 : i32, offset = 0 : i64, domain = #bcir.domain<ram>, hazard = #bcir.hazard<unique>, verify = #bcir.verify<bounds>, bounds = #bcir.bounds<strict> } { %i = bcir.index_range 0 to 0 step 1 }
}

// -----

// claim.count.negative [R7]
bcir.module @m {
  bcir.registry @RES {
    bcir.resource @r1 { rid = 1 : i32, domain_kind = #bcir.domain<ram>, shape = array<i64: 8>, layout = #bcir.layout<soa>, align = 64 : i32 }
  }
  bcir.phase @p0 { id = 0 : i32, deps = [] }
  // expected-error @+1 {{count must be non-negative (got -1)}}
  bcir.claim @c1 attributes { claim_id = 1 : i32, phase = @p0, op = "vector.add", reads = [@r1], writes = [@r1], count = -1 : i64, lane = #bcir.lane<u>, stride_class = #bcir.stride_class<unit>, stride_k = 1 : i32, offset = 0 : i64, domain = #bcir.domain<ram>, hazard = #bcir.hazard<unique>, verify = #bcir.verify<bounds>, bounds = #bcir.bounds<strict> } { %i = bcir.index_range 0 to 0 step 1 }
}

// -----

// claim.offset.negative [R7]
bcir.module @m {
  bcir.registry @RES {
    bcir.resource @r1 { rid = 1 : i32, domain_kind = #bcir.domain<ram>, shape = array<i64: 8>, layout = #bcir.layout<soa>, align = 64 : i32 }
  }
  bcir.phase @p0 { id = 0 : i32, deps = [] }
  // expected-error @+1 {{offset must be non-negative (got -1)}}
  bcir.claim @c1 attributes { claim_id = 1 : i32, phase = @p0, op = "vector.add", reads = [@r1], writes = [@r1], count = 8 : i64, lane = #bcir.lane<u>, stride_class = #bcir.stride_class<unit>, stride_k = 1 : i32, offset = -1 : i64, domain = #bcir.domain<ram>, hazard = #bcir.hazard<unique>, verify = #bcir.verify<bounds>, bounds = #bcir.bounds<strict> } { %i = bcir.index_range 0 to 8 step 1 }
}

// -----

// claim.stride_k.zero [R7]
bcir.module @m {
  bcir.registry @RES {
    bcir.resource @r1 { rid = 1 : i32, domain_kind = #bcir.domain<ram>, shape = array<i64: 8>, layout = #bcir.layout<soa>, align = 64 : i32 }
  }
  bcir.phase @p0 { id = 0 : i32, deps = [] }
  // expected-error @+1 {{stride_k must be positive (got 0)}}
  bcir.claim @c1 attributes { claim_id = 1 : i32, phase = @p0, op = "vector.add", reads = [@r1], writes = [@r1], count = 8 : i64, lane = #bcir.lane<u>, stride_class = #bcir.stride_class<strided>, stride_k = 0 : i32, offset = 0 : i64, domain = #bcir.domain<ram>, hazard = #bcir.hazard<unique>, verify = #bcir.verify<bounds>, bounds = #bcir.bounds<strict> } { %i = bcir.index_range 0 to 8 step 1 }
}

// -----

// claim.stride_k.negative [R7]
bcir.module @m {
  bcir.registry @RES {
    bcir.resource @r1 { rid = 1 : i32, domain_kind = #bcir.domain<ram>, shape = array<i64: 8>, layout = #bcir.layout<soa>, align = 64 : i32 }
  }
  bcir.phase @p0 { id = 0 : i32, deps = [] }
  // expected-error @+1 {{stride_k must be positive (got -2)}}
  bcir.claim @c1 attributes { claim_id = 1 : i32, phase = @p0, op = "vector.add", reads = [@r1], writes = [@r1], count = 8 : i64, lane = #bcir.lane<u>, stride_class = #bcir.stride_class<strided>, stride_k = -2 : i32, offset = 0 : i64, domain = #bcir.domain<ram>, hazard = #bcir.hazard<unique>, verify = #bcir.verify<bounds>, bounds = #bcir.bounds<strict> } { %i = bcir.index_range 0 to 8 step 1 }
}

// -----

// claim.strided.legal [legal] -- extent 0 + (2-1)*4 + 1 = 5 <= 8
bcir.module @m {
  bcir.registry @RES {
    bcir.resource @r1 { rid = 1 : i32, domain_kind = #bcir.domain<ram>, shape = array<i64: 8>, layout = #bcir.layout<soa>, align = 64 : i32 }
  }
  bcir.phase @p0 { id = 0 : i32, deps = [] }
  bcir.claim @c1 attributes { claim_id = 1 : i32, phase = @p0, op = "vector.add", reads = [@r1], writes = [@r1], count = 2 : i64, lane = #bcir.lane<u>, stride_class = #bcir.stride_class<strided>, stride_k = 4 : i32, offset = 0 : i64, domain = #bcir.domain<ram>, hazard = #bcir.hazard<unique>, verify = #bcir.verify<bounds>, bounds = #bcir.bounds<strict> } { %i = bcir.index_range 0 to 2 step 1 }
}

// -----

// claim.strided.overrun [R7]
bcir.module @m {
  bcir.registry @RES {
    bcir.resource @r1 { rid = 1 : i32, domain_kind = #bcir.domain<ram>, shape = array<i64: 8>, layout = #bcir.layout<soa>, align = 64 : i32 }
  }
  bcir.phase @p0 { id = 0 : i32, deps = [] }
  // expected-error @+1 {{R7: claim c1 read of @r1 overruns the resource (extent 9 > 8)}}
  bcir.claim @c1 attributes { claim_id = 1 : i32, phase = @p0, op = "vector.add", reads = [@r1], writes = [@r1], count = 3 : i64, lane = #bcir.lane<u>, stride_class = #bcir.stride_class<strided>, stride_k = 4 : i32, offset = 0 : i64, domain = #bcir.domain<ram>, hazard = #bcir.hazard<unique>, verify = #bcir.verify<bounds>, bounds = #bcir.bounds<strict> } { %i = bcir.index_range 0 to 3 step 1 }
}

// -----

// claim.extent.overflow [R7]
bcir.module @m {
  bcir.registry @RES {
    bcir.resource @r1 { rid = 1 : i32, domain_kind = #bcir.domain<ram>, shape = array<i64: 8>, layout = #bcir.layout<soa>, align = 64 : i32 }
  }
  bcir.phase @p0 { id = 0 : i32, deps = [] }
  // expected-error @+1 {{R7: affine access extent exceeds signed 64-bit range}}
  bcir.claim @c1 attributes { claim_id = 1 : i32, phase = @p0, op = "vector.add", reads = [@r1], writes = [@r1], count = 4611686018427387904 : i64, lane = #bcir.lane<u>, stride_class = #bcir.stride_class<strided>, stride_k = 4 : i32, offset = 0 : i64, domain = #bcir.domain<ram>, hazard = #bcir.hazard<unique>, verify = #bcir.verify<bounds>, bounds = #bcir.bounds<strict> } { %i = bcir.index_range 0 to 4611686018427387904 step 1 }
}

// -----

// claim.undeclared_resource [R2]
bcir.module @m {
  bcir.registry @RES {
    bcir.resource @r1 { rid = 1 : i32, domain_kind = #bcir.domain<ram>, shape = array<i64: 8>, layout = #bcir.layout<soa>, align = 64 : i32 }
  }
  bcir.phase @p0 { id = 0 : i32, deps = [] }
  // expected-error @+1 {{R2: claim c1 reads undeclared resource @r999}}
  bcir.claim @c1 attributes { claim_id = 1 : i32, phase = @p0, op = "vector.add", reads = [@r1, @r999], writes = [@r1], count = 8 : i64, lane = #bcir.lane<u>, stride_class = #bcir.stride_class<unit>, stride_k = 1 : i32, offset = 0 : i64, domain = #bcir.domain<ram>, hazard = #bcir.hazard<unique>, verify = #bcir.verify<bounds>, bounds = #bcir.bounds<strict> } { %i = bcir.index_range 0 to 8 step 1 }
}

// -----

// lane.tile_on_unit [R6]
bcir.module @m {
  bcir.registry @RES {
    bcir.resource @r1 { rid = 1 : i32, domain_kind = #bcir.domain<ram>, shape = array<i64: 8>, layout = #bcir.layout<soa>, align = 64 : i32 }
  }
  bcir.phase @p0 { id = 0 : i32, deps = [] }
  // expected-error @+1 {{R6: claim c1 lane illegal for its stride class}}
  bcir.claim @c1 attributes { claim_id = 1 : i32, phase = @p0, op = "vector.add", reads = [@r1], writes = [@r1], count = 8 : i64, lane = #bcir.lane<t>, stride_class = #bcir.stride_class<unit>, stride_k = 1 : i32, offset = 0 : i64, domain = #bcir.domain<ram>, hazard = #bcir.hazard<unique>, verify = #bcir.verify<bounds>, bounds = #bcir.bounds<strict> } { %i = bcir.index_range 0 to 8 step 1 }
}

// -----

// phase.duplicate_id [R4]
bcir.module @m {
  bcir.registry @RES {
    bcir.resource @r1 { rid = 1 : i32, domain_kind = #bcir.domain<ram>, shape = array<i64: 8>, layout = #bcir.layout<soa>, align = 64 : i32 }
  }
  bcir.phase @p0 { id = 0 : i32, deps = [] }
  // expected-error @+1 {{R4: phase @q0 duplicates phase id 0 of @p0}}
  bcir.phase @q0 { id = 0 : i32, deps = [] }
  bcir.claim @c1 attributes { claim_id = 1 : i32, phase = @p0, op = "vector.add", reads = [@r1], writes = [@r1], count = 8 : i64, lane = #bcir.lane<u>, stride_class = #bcir.stride_class<unit>, stride_k = 1 : i32, offset = 0 : i64, domain = #bcir.domain<ram>, hazard = #bcir.hazard<unique>, verify = #bcir.verify<bounds>, bounds = #bcir.bounds<strict> } { %i = bcir.index_range 0 to 8 step 1 }
}

// -----

// phase.dangling_dep [R4]
bcir.module @m {
  bcir.registry @RES {
    bcir.resource @r1 { rid = 1 : i32, domain_kind = #bcir.domain<ram>, shape = array<i64: 8>, layout = #bcir.layout<soa>, align = 64 : i32 }
  }
  // expected-error @+1 {{R4: phase @p0 depends on undeclared phase @p9}}
  bcir.phase @p0 { id = 0 : i32, deps = [@p9] }
  bcir.claim @c1 attributes { claim_id = 1 : i32, phase = @p0, op = "vector.add", reads = [@r1], writes = [@r1], count = 8 : i64, lane = #bcir.lane<u>, stride_class = #bcir.stride_class<unit>, stride_k = 1 : i32, offset = 0 : i64, domain = #bcir.domain<ram>, hazard = #bcir.hazard<unique>, verify = #bcir.verify<bounds>, bounds = #bcir.bounds<strict> } { %i = bcir.index_range 0 to 8 step 1 }
}

// -----

// phase.self_dep [R4]
bcir.module @m {
  bcir.registry @RES {
    bcir.resource @r1 { rid = 1 : i32, domain_kind = #bcir.domain<ram>, shape = array<i64: 8>, layout = #bcir.layout<soa>, align = 64 : i32 }
  }
  // expected-error @+1 {{R4: phase dependency cycle through @p0}}
  bcir.phase @p0 { id = 0 : i32, deps = [@p0] }
  bcir.claim @c1 attributes { claim_id = 1 : i32, phase = @p0, op = "vector.add", reads = [@r1], writes = [@r1], count = 8 : i64, lane = #bcir.lane<u>, stride_class = #bcir.stride_class<unit>, stride_k = 1 : i32, offset = 0 : i64, domain = #bcir.domain<ram>, hazard = #bcir.hazard<unique>, verify = #bcir.verify<bounds>, bounds = #bcir.bounds<strict> } { %i = bcir.index_range 0 to 8 step 1 }
}

// -----

// phase.cycle [R4]
bcir.module @m {
  bcir.registry @RES {
    bcir.resource @r1 { rid = 1 : i32, domain_kind = #bcir.domain<ram>, shape = array<i64: 8>, layout = #bcir.layout<soa>, align = 64 : i32 }
  }
  // expected-error @+1 {{R4: phase dependency cycle through @p0}}
  bcir.phase @p0 { id = 0 : i32, deps = [@p1] }
  bcir.phase @p1 { id = 1 : i32, deps = [@p0] }
  bcir.claim @c1 attributes { claim_id = 1 : i32, phase = @p0, op = "vector.add", reads = [@r1], writes = [@r1], count = 8 : i64, lane = #bcir.lane<u>, stride_class = #bcir.stride_class<unit>, stride_k = 1 : i32, offset = 0 : i64, domain = #bcir.domain<ram>, hazard = #bcir.hazard<unique>, verify = #bcir.verify<bounds>, bounds = #bcir.bounds<strict> } { %i = bcir.index_range 0 to 8 step 1 }
}

// -----

// phase.order.ids_out_of_dependency_order [legal] -- legal; the canonical order is [1, 0] on both rails (schedule_phase_order.mlir pins -bcir-schedule's exec_order to it)
bcir.module @m {
  bcir.registry @RES {
    bcir.resource @r1 { rid = 1 : i32, domain_kind = #bcir.domain<ram>, shape = array<i64: 8>, layout = #bcir.layout<soa>, align = 64 : i32 }
  }
  bcir.phase @p1 { id = 1 : i32, deps = [] }
  bcir.phase @p0 { id = 0 : i32, deps = [@p1] }
  bcir.claim @c1 attributes { claim_id = 1 : i32, phase = @p0, op = "vector.add", reads = [@r1], writes = [@r1], count = 8 : i64, lane = #bcir.lane<u>, stride_class = #bcir.stride_class<unit>, stride_k = 1 : i32, offset = 0 : i64, domain = #bcir.domain<ram>, hazard = #bcir.hazard<unique>, verify = #bcir.verify<bounds>, bounds = #bcir.bounds<strict> } { %i = bcir.index_range 0 to 8 step 1 }
  bcir.claim @c2 attributes { claim_id = 2 : i32, phase = @p1, op = "vector.add", reads = [@r1], writes = [@r1], count = 8 : i64, lane = #bcir.lane<u>, stride_class = #bcir.stride_class<unit>, stride_k = 1 : i32, offset = 0 : i64, domain = #bcir.domain<ram>, hazard = #bcir.hazard<unique>, verify = #bcir.verify<bounds>, bounds = #bcir.bounds<strict> } { %i = bcir.index_range 0 to 8 step 1 }
}

// -----

// domain.hbm_only [legal]
bcir.module @m {
  bcir.registry @RES {
    bcir.resource @r1 { rid = 1 : i32, domain_kind = #bcir.domain<hbm>, shape = array<i64: 8>, layout = #bcir.layout<soa>, align = 64 : i32 }
  }
  bcir.phase @p0 { id = 0 : i32, deps = [] }
  bcir.claim @c1 attributes { claim_id = 1 : i32, phase = @p0, op = "vector.add", reads = [@r1], writes = [@r1], count = 8 : i64, lane = #bcir.lane<u>, stride_class = #bcir.stride_class<unit>, stride_k = 1 : i32, offset = 0 : i64, domain = #bcir.domain<hbm>, hazard = #bcir.hazard<unique>, verify = #bcir.verify<bounds>, bounds = #bcir.bounds<strict> } { %i = bcir.index_range 0 to 8 step 1 }
}

// -----

// domain.host_mix [legal] -- RAM/HBM are mutually addressable host memory: a RAM claim may accumulate into HBM
bcir.module @m {
  bcir.registry @RES {
    bcir.resource @r1 { rid = 1 : i32, domain_kind = #bcir.domain<ram>, shape = array<i64: 8>, layout = #bcir.layout<soa>, align = 64 : i32 }
    bcir.resource @r2 { rid = 2 : i32, domain_kind = #bcir.domain<hbm>, shape = array<i64: 8>, layout = #bcir.layout<soa>, align = 64 : i32 }
  }
  bcir.phase @p0 { id = 0 : i32, deps = [] }
  bcir.claim @c1 attributes { claim_id = 1 : i32, phase = @p0, op = "vector.add", reads = [@r1], writes = [@r2], count = 8 : i64, lane = #bcir.lane<u>, stride_class = #bcir.stride_class<unit>, stride_k = 1 : i32, offset = 0 : i64, domain = #bcir.domain<ram>, hazard = #bcir.hazard<unique>, verify = #bcir.verify<bounds>, bounds = #bcir.bounds<strict> } { %i = bcir.index_range 0 to 8 step 1 }
}

// -----

// domain.unbacked [R3]
bcir.module @m {
  bcir.registry @RES {
    bcir.resource @r1 { rid = 1 : i32, domain_kind = #bcir.domain<hbm>, shape = array<i64: 8>, layout = #bcir.layout<soa>, align = 64 : i32 }
  }
  bcir.phase @p0 { id = 0 : i32, deps = [] }
  // expected-error @+1 {{R3: claim c1 declares a domain not backed by any touched resource}}
  bcir.claim @c1 attributes { claim_id = 1 : i32, phase = @p0, op = "vector.add", reads = [@r1], writes = [@r1], count = 8 : i64, lane = #bcir.lane<u>, stride_class = #bcir.stride_class<unit>, stride_k = 1 : i32, offset = 0 : i64, domain = #bcir.domain<ram>, hazard = #bcir.hazard<unique>, verify = #bcir.verify<bounds>, bounds = #bcir.bounds<strict> } { %i = bcir.index_range 0 to 8 step 1 }
}

// -----

// domain.ram_claim_reaches_mmio [R3]
bcir.module @m {
  bcir.registry @RES {
    bcir.resource @r1 { rid = 1 : i32, domain_kind = #bcir.domain<ram>, shape = array<i64: 8>, layout = #bcir.layout<soa>, align = 64 : i32 }
    bcir.resource @r2 { rid = 2 : i32, domain_kind = #bcir.domain<mmio>, shape = array<i64: 1>, layout = #bcir.layout<soa>, align = 64 : i32 }
  }
  bcir.phase @p0 { id = 0 : i32, deps = [] }
  // expected-error @+1 {{R3: claim c1 reads @r2 (domain mmio) does not match the claim domain ram -- the resource is in a device-isolated domain}}
  bcir.claim @c1 attributes { claim_id = 1 : i32, phase = @p0, op = "vector.add", reads = [@r1, @r2], writes = [@r1], count = 1 : i64, lane = #bcir.lane<u>, stride_class = #bcir.stride_class<unit>, stride_k = 1 : i32, offset = 0 : i64, domain = #bcir.domain<ram>, hazard = #bcir.hazard<unique>, verify = #bcir.verify<bounds>, bounds = #bcir.bounds<strict> } { %i = bcir.index_range 0 to 1 step 1 }
}

// -----

// domain.mmio_claim_with_ram_operand [legal] -- the shape of every cfront MMIO write: the RAM value stored into the register
bcir.module @m {
  bcir.registry @RES {
    bcir.resource @r1 { rid = 1 : i32, domain_kind = #bcir.domain<ram>, shape = array<i64: 8>, layout = #bcir.layout<soa>, align = 64 : i32 }
    bcir.resource @r2 { rid = 2 : i32, domain_kind = #bcir.domain<mmio>, shape = array<i64: 1>, layout = #bcir.layout<soa>, align = 64 : i32 }
  }
  bcir.phase @p0 { id = 0 : i32, deps = [] }
  bcir.claim @c1 attributes { claim_id = 1 : i32, phase = @p0, op = "vector.add", reads = [@r1], writes = [@r2], count = 1 : i64, lane = #bcir.lane<u>, stride_class = #bcir.stride_class<unit>, stride_k = 1 : i32, offset = 0 : i64, domain = #bcir.domain<mmio>, hazard = #bcir.hazard<barriered>, verify = #bcir.verify<bounds>, bounds = #bcir.bounds<strict>, is_volatile = true } { %i = bcir.index_range 0 to 1 step 1 }
}

// -----

// domain.mmio_write_unique_hazard [R3]
bcir.module @m {
  bcir.registry @RES {
    bcir.resource @r2 { rid = 2 : i32, domain_kind = #bcir.domain<mmio>, shape = array<i64: 1>, layout = #bcir.layout<soa>, align = 64 : i32 }
  }
  bcir.phase @p0 { id = 0 : i32, deps = [] }
  // expected-error @+1 {{R3: claim c1 MMIO write to @r2 requires an atomic/barriered hazard}}
  bcir.claim @c1 attributes { claim_id = 1 : i32, phase = @p0, op = "vector.add", reads = [@r2], writes = [@r2], count = 1 : i64, lane = #bcir.lane<u>, stride_class = #bcir.stride_class<unit>, stride_k = 1 : i32, offset = 0 : i64, domain = #bcir.domain<mmio>, hazard = #bcir.hazard<unique>, verify = #bcir.verify<bounds>, bounds = #bcir.bounds<strict> } { %i = bcir.index_range 0 to 1 step 1 }
}

// -----

// domain.nvm_stage_to_vram [legal] -- NVM is a memory TIER the HAM fabric stages across, not a device-isolated domain: the law rail's former 'NVM cell' isolation had no fixture, and the oracle's tier model won
bcir.module @m {
  bcir.registry @RES {
    bcir.resource @r1 { rid = 1 : i32, domain_kind = #bcir.domain<nvm>, shape = array<i64: 8>, layout = #bcir.layout<soa>, align = 64 : i32 }
    bcir.resource @r2 { rid = 2 : i32, domain_kind = #bcir.domain<vram>, shape = array<i64: 8>, layout = #bcir.layout<soa>, align = 64 : i32 }
  }
  bcir.phase @p0 { id = 0 : i32, deps = [] }
  bcir.claim @c1 attributes { claim_id = 1 : i32, phase = @p0, op = "vector.add", reads = [@r1], writes = [@r2], count = 8 : i64, lane = #bcir.lane<u>, stride_class = #bcir.stride_class<unit>, stride_k = 1 : i32, offset = 0 : i64, domain = #bcir.domain<vram>, hazard = #bcir.hazard<unique>, verify = #bcir.verify<bounds>, bounds = #bcir.bounds<strict> } { %i = bcir.index_range 0 to 8 step 1 }
}

// -----

// domain.mmio_claim_nvm_operand [legal] -- a device register written from a tier operand: only the resource side is isolated
bcir.module @m {
  bcir.registry @RES {
    bcir.resource @r2 { rid = 2 : i32, domain_kind = #bcir.domain<mmio>, shape = array<i64: 1>, layout = #bcir.layout<soa>, align = 64 : i32 }
    bcir.resource @r3 { rid = 3 : i32, domain_kind = #bcir.domain<nvm>, shape = array<i64: 1>, layout = #bcir.layout<soa>, align = 64 : i32 }
  }
  bcir.phase @p0 { id = 0 : i32, deps = [] }
  bcir.claim @c1 attributes { claim_id = 1 : i32, phase = @p0, op = "vector.add", reads = [@r3], writes = [@r2], count = 1 : i64, lane = #bcir.lane<u>, stride_class = #bcir.stride_class<unit>, stride_k = 1 : i32, offset = 0 : i64, domain = #bcir.domain<mmio>, hazard = #bcir.hazard<barriered>, verify = #bcir.verify<bounds>, bounds = #bcir.bounds<strict>, is_volatile = true } { %i = bcir.index_range 0 to 1 step 1 }
}

// -----

// domain.ham_on_mmio [R3]
bcir.module @m {
  bcir.registry @RES {
    // expected-error @+1 {{R3: resource r2 HAM access is illegal in the MMIO domain}}
    bcir.resource @r2 { rid = 2 : i32, domain_kind = #bcir.domain<mmio>, shape = array<i64: 1>, layout = #bcir.layout<soa>, align = 64 : i32, access = #bcir.access<ham> }
  }
  bcir.phase @p0 { id = 0 : i32, deps = [] }
}

// -----

// target.legal [legal]
bcir.module @m {
bcir.target.capability @cpu { triple = "x86_64-avx512", isa_features = [], lane_widths = array<i64: 1, 8, 16>, cacheline = 64 : i32, elem_bytes = 4 : i32 }
}

// -----

// target.cacheline.not_pow2 [R8] -- an op-level check on the law rail; the oracle refuses at construction -- filed under the cost law the descriptor feeds
bcir.module @m {
  // expected-error @+1 {{cacheline must be a positive power of two (got 48)}}
  bcir.target.capability @cpu { triple = "x86_64-avx512", isa_features = [], lane_widths = array<i64: 1, 8>, cacheline = 48 : i32, elem_bytes = 4 : i32 }
}

// -----

// target.lane_widths.empty [R8]
bcir.module @m {
  // expected-error @+1 {{lane_widths must contain at least one positive width}}
  bcir.target.capability @cpu { triple = "x86_64-avx512", isa_features = [], lane_widths = array<i64>, cacheline = 64 : i32, elem_bytes = 4 : i32 }
}

// -----

// target.lane_width.zero [R8]
bcir.module @m {
  // expected-error @+1 {{lane widths must be positive (got 0)}}
  bcir.target.capability @cpu { triple = "x86_64-avx512", isa_features = [], lane_widths = array<i64: 1, 0>, cacheline = 64 : i32, elem_bytes = 4 : i32 }
}

// -----

// target.elem_bytes.zero [R8]
bcir.module @m {
  // expected-error @+1 {{affinity_domains, mem_channels, mem_unit, and elem_bytes must be positive}}
  bcir.target.capability @cpu { triple = "x86_64-avx512", isa_features = [], lane_widths = array<i64: 1, 8>, cacheline = 64 : i32, elem_bytes = 0 : i32 }
}

// -----

// addr.i64_under_x86_64 [legal]
bcir.module @m {
  bcir.target.capability @cpu { triple = "x86_64-avx512", isa_features = [], lane_widths = array<i64: 1, 8, 16>, cacheline = 64 : i32, elem_bytes = 4 : i32 }
  func.func @f(%addr: i64) -> i32 {
    %v = bcir.volatile_load %addr : i64 -> i32
    return %v : i32
  }
}

// -----

// addr.i32_under_x86_64 [R12]
bcir.module @m {
  bcir.target.capability @cpu { triple = "x86_64-avx512", isa_features = [], lane_widths = array<i64: 1, 8, 16>, cacheline = 64 : i32, elem_bytes = 4 : i32 }
  func.func @f(%addr: i32) -> i32 {
    // expected-error @+1 {{R12: the device-register address is 32 bits but the target 'x86_64-avx512' addresses 64-bit pointers; the inttoptr lowering would leave it zero-extended}}
    %v = bcir.volatile_load %addr : i32 -> i32
    return %v : i32
  }
}

// -----

// addr.i32_store_under_aarch64 [R12]
bcir.module @m {
  bcir.target.capability @cpu { triple = "aarch64-sve", isa_features = [], lane_widths = array<i64: 1, 8, 16>, cacheline = 64 : i32, elem_bytes = 4 : i32 }
  func.func @f(%v: i32, %addr: i32) {
    // expected-error @+1 {{R12: the device-register address is 32 bits but the target 'aarch64-sve' addresses 64-bit}}
    bcir.volatile_store %v, %addr : i32, i32
    return
  }
}

// -----

// addr.i32_under_riscv32 [legal]
bcir.module @m {
  bcir.target.capability @cpu { triple = "riscv32-unknown-elf", isa_features = [], lane_widths = array<i64: 1, 8, 16>, cacheline = 64 : i32, elem_bytes = 4 : i32 }
  func.func @f(%addr: i32) -> i32 {
    %v = bcir.volatile_load %addr : i32 -> i32
    return %v : i32
  }
}

// -----

// addr.i64_under_riscv32 [R12]
bcir.module @m {
  bcir.target.capability @cpu { triple = "riscv32-unknown-elf", isa_features = [], lane_widths = array<i64: 1, 8, 16>, cacheline = 64 : i32, elem_bytes = 4 : i32 }
  func.func @f(%addr: i64) -> i32 {
    // expected-error @+1 {{R12: the device-register address is 64 bits but the target 'riscv32-unknown-elf' addresses 32-bit pointers; the inttoptr lowering would leave it truncated}}
    %v = bcir.volatile_load %addr : i64 -> i32
    return %v : i32
  }
}

// -----

// addr.rmw_i32_under_nvptx64 [R12]
bcir.module @m {
  bcir.target.capability @cpu { triple = "nvptx64-warp", isa_features = [], lane_widths = array<i64: 1, 8, 16>, cacheline = 64 : i32, elem_bytes = 4 : i32 }
  func.func @f(%v: i32, %addr: i32) -> i32 {
    // expected-error @+1 {{R12: the object address is 32 bits but the target 'nvptx64-warp' addresses 64-bit pointers}}
    %o = bcir.atomic_rmw "add" %v, %addr : i32, i32 -> i32
    return %o : i32
  }
}

// -----

// addr.cas_i32_under_bpf [R12]
bcir.module @m {
  bcir.target.capability @cpu { triple = "bpfel", isa_features = [], lane_widths = array<i64: 1, 8, 16>, cacheline = 64 : i32, elem_bytes = 4 : i32 }
  func.func @f(%e: i32, %d: i32, %addr: i32) -> i32 {
    // expected-error @+1 {{R12: the object address is 32 bits but the target 'bpfel' addresses 64-bit pointers}}
    %o = bcir.atomic_cas %e, %d, %addr : i32, i32, i32 -> i32
    return %o : i32
  }
}

// -----

// addr.cas_i64_under_bpf [legal]
bcir.module @m {
  bcir.target.capability @cpu { triple = "bpfel", isa_features = [], lane_widths = array<i64: 1, 8, 16>, cacheline = 64 : i32, elem_bytes = 4 : i32 }
  func.func @f(%e: i32, %d: i32, %addr: i64) -> i32 {
    %o = bcir.atomic_cas %e, %d, %addr : i32, i32, i64 -> i32
    return %o : i32
  }
}

// -----

// addr.i32_under_arm64_32 [legal] -- the watchOS ILP32 ABI: a 32-bit pointer on a 64-bit family (the family prefix claimed it as 64; #762 review)
bcir.module @m {
  bcir.target.capability @cpu { triple = "arm64_32-apple-watchos", isa_features = [], lane_widths = array<i64: 1, 8, 16>, cacheline = 64 : i32, elem_bytes = 4 : i32 }
  func.func @f(%addr: i32) -> i32 {
    %v = bcir.volatile_load %addr : i32 -> i32
    return %v : i32
  }
}

// -----

// addr.i64_under_arm64_32 [R12]
bcir.module @m {
  bcir.target.capability @cpu { triple = "arm64_32-apple-watchos", isa_features = [], lane_widths = array<i64: 1, 8, 16>, cacheline = 64 : i32, elem_bytes = 4 : i32 }
  func.func @f(%addr: i64) -> i32 {
    // expected-error @+1 {{R12: the device-register address is 64 bits but the target 'arm64_32-apple-watchos' addresses 32-bit pointers; the inttoptr lowering would leave it truncated}}
    %v = bcir.volatile_load %addr : i64 -> i32
    return %v : i32
  }
}

// -----

// addr.i16_below_the_floor [R12] -- the floor holds whatever the target (an unknown one here): the op verifier on the law rail, R12 on the oracle -- and no tabulated width is below it (#762 review)
bcir.module @m {
  bcir.target.capability @cpu { triple = "x", isa_features = [], lane_widths = array<i64: 1, 8, 16>, cacheline = 64 : i32, elem_bytes = 4 : i32 }
  func.func @f(%addr: i16) -> i32 {
    // expected-error @+1 {{the device-register address must be an integer of at least pointer width (>= 32 bits; got 'i16')}}
    %v = bcir.volatile_load %addr : i16 -> i32
    return %v : i32
  }
}

// -----

// addr.i32_unknown_triple [legal] -- an architecture the table does not know: the law is vacuous, the >= 32-bit floor holds
bcir.module @m {
  bcir.target.capability @cpu { triple = "x", isa_features = [], lane_widths = array<i64: 1, 8, 16>, cacheline = 64 : i32, elem_bytes = 4 : i32 }
  func.func @f(%addr: i32) -> i32 {
    %v = bcir.volatile_load %addr : i32 -> i32
    return %v : i32
  }
}

// -----

// addr.i32_no_target [legal] -- no target in scope: only the floor
bcir.module @m {
  func.func @f(%addr: i32) -> i32 {
    %v = bcir.volatile_load %addr : i32 -> i32
    return %v : i32
  }
}

// -----

// manifest.legal [legal]
bcir.module @m {
  bcir.kbcir.provenance_manifest @man { digest = 6843787964663692581 : i64, score = 7808 : i64, n_artifacts = 2 : i64, reproduced = true, m_module = 7127522701151166272 : i64, m_target = 5192828792194564141 : i64, m_theta = 1870846051561339781 : i64, m_policy = 4048695575545564183 : i64, artifact_names = ["cal_gen", "map_gen"], artifact_gens = array<i64: 4, 2> }
}

// -----

// manifest.legal.no_artifacts [legal]
bcir.module @m {
  bcir.kbcir.provenance_manifest @man { digest = 8915526058458340485 : i64, score = 7808 : i64, n_artifacts = 0 : i64, reproduced = true, m_module = 7127522701151166272 : i64, m_target = 5192828792194564141 : i64, m_theta = 1870846051561339781 : i64, m_policy = 4048695575545564183 : i64 }
}

// -----

// manifest.unsorted_artifacts [R13] -- the digest was folded in the declared order, which the old law rail accepted
bcir.module @m {
  // expected-error @+1 {{R13: manifest artifact names must be sorted and unique ('map_gen' precedes 'cal_gen')}}
  bcir.kbcir.provenance_manifest @man { digest = 4654169102590460869 : i64, score = 7808 : i64, n_artifacts = 2 : i64, reproduced = true, m_module = 7127522701151166272 : i64, m_target = 5192828792194564141 : i64, m_theta = 1870846051561339781 : i64, m_policy = 4048695575545564183 : i64, artifact_names = ["map_gen", "cal_gen"], artifact_gens = array<i64: 2, 4> }
}

// -----

// manifest.duplicate_artifact [R13]
bcir.module @m {
  // expected-error @+1 {{R13: manifest artifact names must be sorted and unique ('cal_gen' precedes 'cal_gen')}}
  bcir.kbcir.provenance_manifest @man { digest = 7002654814637788083 : i64, score = 7808 : i64, n_artifacts = 2 : i64, reproduced = true, m_module = 7127522701151166272 : i64, m_target = 5192828792194564141 : i64, m_theta = 1870846051561339781 : i64, m_policy = 4048695575545564183 : i64, artifact_names = ["cal_gen", "cal_gen"], artifact_gens = array<i64: 4, 2> }
}

// -----

// manifest.arity_mismatch [R13] -- a (name, generation) pair cannot mismatch its own arity in the oracle's object model
bcir.module @m {
  // expected-error @+1 {{R13: manifest artifact_names/artifact_gens arity mismatch (1 names, 2 generations)}}
  bcir.kbcir.provenance_manifest @man { digest = 6843787964663692581 : i64, score = 7808 : i64, n_artifacts = 1 : i64, reproduced = true, m_module = 7127522701151166272 : i64, m_target = 5192828792194564141 : i64, m_theta = 1870846051561339781 : i64, m_policy = 4048695575545564183 : i64, artifact_names = ["cal_gen"], artifact_gens = array<i64: 4, 2> }
}

// -----

// manifest.absent_theta [R13] -- a manifest inside a module carrying a claim graph declares m_theta with no theta op; the oracle's verify_manifest recomputes from the inputs it is handed and cannot be asked about an object that is not there
bcir.module @m {
  bcir.registry @RES {
    bcir.resource @r1 { rid = 1 : i32, domain_kind = #bcir.domain<ram>, shape = array<i64: 8>, layout = #bcir.layout<soa> }
  }
  bcir.phase @p0 { id = 0 : i32, deps = [] }
  bcir.claim @c1 attributes { claim_id = 1 : i32, phase = @p0, op = "vector.add", reads = [@r1], writes = [@r1], count = 8 : i64, lane = #bcir.lane<u>, stride_class = #bcir.stride_class<unit>, stride_k = 1 : i32, offset = 0 : i64, domain = #bcir.domain<ram>, hazard = #bcir.hazard<unique>, verify = #bcir.verify<bounds>, bounds = #bcir.bounds<strict> } { %i = bcir.index_range 0 to 8 step 1 }
  // expected-error @+1 {{R13: manifest declares m_theta but the module carries no kbcir.theta to recompute it from}}
  bcir.kbcir.provenance_manifest @man { digest = 5568577758313728278 : i64, score = 7808 : i64, n_artifacts = 0 : i64, reproduced = true, m_theta = 1870846051561339781 : i64 }
}

// -----

// manifest.theta_present [legal] -- the cool theta's hash, recomputed from the kbcir.theta op it sits beside
bcir.module @m {
  bcir.kbcir.theta @theta { thermal = 0 : i32 }
  bcir.kbcir.provenance_manifest @man { digest = 5568577758313728278 : i64, score = 7808 : i64, n_artifacts = 0 : i64, reproduced = true, m_theta = 1870846051561339781 : i64 }
}

// -----

// portfolio.certified_gen1 [legal]
bcir.module @m {
  bcir.kbcir.policy @latency { mode = #bcir.policy_mode<latency>, weights = array<i64: 2, 2, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1> }
  bcir.kbcir.portfolio @pf { policies = [@latency], gens = array<i64: 1>, certified = array<i64: 1> }
}

// -----

// portfolio.certified_gen0 [R13]
bcir.module @m {
  bcir.kbcir.policy @latency { mode = #bcir.policy_mode<latency>, weights = array<i64: 2, 2, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1> }
  // expected-error @+1 {{R13: portfolio generation tags must be >= 1}}
  bcir.kbcir.portfolio @pf { policies = [@latency], gens = array<i64: 0>, certified = array<i64: 1> }
}

// -----

// portfolio.promoted_without_certificate [R13]
bcir.module @m {
  bcir.kbcir.policy @latency { mode = #bcir.policy_mode<latency>, weights = array<i64: 2, 2, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1> }
  // expected-error @+1 {{R13: promoted policy @latency (gen 2) has no admitting replay certificate}}
  bcir.kbcir.portfolio @pf { policies = [@latency], gens = array<i64: 2>, certified = array<i64: 1> }
}

// -----

// portfolio.promoted_uncertified_without_certificate [R13] -- the oracle used to skip uncertified entries; a promotion is witnessed or it did not happen
bcir.module @m {
  bcir.kbcir.policy @latency { mode = #bcir.policy_mode<latency>, weights = array<i64: 2, 2, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1> }
  // expected-error @+1 {{R13: promoted policy @latency (gen 2) has no admitting replay certificate}}
  bcir.kbcir.portfolio @pf { policies = [@latency], gens = array<i64: 2>, certified = array<i64: 0> }
}

// -----

// portfolio.promoted_with_certificate [legal]
bcir.module @m {
  bcir.kbcir.policy @latency { mode = #bcir.policy_mode<latency>, weights = array<i64: 2, 2, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1> }
  bcir.kbcir.replay_certificate @rc0 { candidate = @latency, incumbent = @latency, episodes = 4 : i64, regressions = 0 : i64, admitted = true }
  bcir.kbcir.portfolio @pf { policies = [@latency], gens = array<i64: 2>, certified = array<i64: 1> }
}

// -----

// calibration.constants_match [legal]
bcir.module @m {
  bcir.target.capability @cpu { triple = "x86_64-avx512", isa_features = [], lane_widths = array<i64: 1, 8, 16>, cacheline = 64 : i32, elem_bytes = 4 : i32, gather_penalty = 32 : i32, base_overhead = 4 : i32, mem_unit = 1 : i32, cal_gen = 1 : i64 }
  bcir.kbcir.calibration @cal { target = @cpu, cal_gen = 1 : i64, samples = 5 : i64, provenance = "host", stream_q8 = 256 : i64, strided_q8 = 256 : i64, random_q8 = 8192 : i64, compute_q8 = 256 : i64 }
}

// -----

// calibration.constants_drift [R13]
bcir.module @m {
  // expected-error @+1 {{R13: capability @cpu constants drifted from calibration certificate @cal (gather_penalty 32 vs certified 64, base_overhead 4 vs certified 4, mem_unit 1 vs 1)}}
  bcir.target.capability @cpu { triple = "x86_64-avx512", isa_features = [], lane_widths = array<i64: 1, 8, 16>, cacheline = 64 : i32, elem_bytes = 4 : i32, gather_penalty = 32 : i32, base_overhead = 4 : i32, mem_unit = 1 : i32, cal_gen = 1 : i64 }
  bcir.kbcir.calibration @cal { target = @cpu, cal_gen = 1 : i64, samples = 5 : i64, provenance = "host", stream_q8 = 256 : i64, strided_q8 = 256 : i64, random_q8 = 16384 : i64, compute_q8 = 256 : i64 }
}

// -----

// calibration.strided_q8_overflow [R13] -- a ratio above INT64_MAX/4 passes R8's floor; the oracle prices in unbounded integers and sees the drift, the law rail refuses the derivation it cannot represent instead of overflowing (#762 review)
bcir.module @m {
  // expected-error @+1 {{R13: capability @cpu certificate @cal strided_q8 4611686018427387904 overflows the base_overhead derivation (4*strided_q8 exceeds signed 64-bit range)}}
  bcir.target.capability @cpu { triple = "x86_64-avx512", isa_features = [], lane_widths = array<i64: 1, 8, 16>, cacheline = 64 : i32, elem_bytes = 4 : i32, gather_penalty = 32 : i32, base_overhead = 4 : i32, mem_unit = 1 : i32, cal_gen = 1 : i64 }
  bcir.kbcir.calibration @cal { target = @cpu, cal_gen = 1 : i64, samples = 5 : i64, provenance = "host", stream_q8 = 256 : i64, strided_q8 = 4611686018427387904 : i64, random_q8 = 8192 : i64, compute_q8 = 256 : i64 }
}

// -----

// m5.binary.legal [legal] -- the NVMe SQE header
bcir.module @m {
  bcir.binary.format @f attributes { endianness = "little", alignment_bits = 8 : i64 } {
    bcir.binary.field @opcode { name = "opcode", offset_bits = 0 : i64, width_bits = 8 : i64, kind = "u", semantic = "" }
    bcir.binary.field @command_id { name = "command_id", offset_bits = 16 : i64, width_bits = 16 : i64, kind = "u", semantic = "" }
    bcir.binary.field @namespace_id { name = "namespace_id", offset_bits = 32 : i64, width_bits = 32 : i64, kind = "u", semantic = "" }
    bcir.binary.record @r { name = "r", fields = [@opcode, @command_id, @namespace_id], size_bits = 64 : i64 }
  }
}

// -----

// m5.field.width_zero [R21]
bcir.module @m {
  bcir.binary.format @f attributes { endianness = "little", alignment_bits = 8 : i64 } {
    // expected-error @+1 {{field 'a': width_bits must be positive (got 0)}}
    bcir.binary.field @a { name = "a", offset_bits = 0 : i64, width_bits = 0 : i64, kind = "u", semantic = "" }
    bcir.binary.record @r { name = "r", fields = [@a], size_bits = 0 : i64 }
  }
}

// -----

// m5.field.offset_negative [R21]
bcir.module @m {
  bcir.binary.format @f attributes { endianness = "little", alignment_bits = 8 : i64 } {
    // expected-error @+1 {{field 'a': offset_bits must be non-negative (got -8)}}
    bcir.binary.field @a { name = "a", offset_bits = -8 : i64, width_bits = 8 : i64, kind = "u", semantic = "" }
    bcir.binary.record @r { name = "r", fields = [@a], size_bits = 0 : i64 }
  }
}

// -----

// m5.field.kind_unknown [R21]
bcir.module @m {
  bcir.binary.format @f attributes { endianness = "little", alignment_bits = 8 : i64 } {
    // expected-error @+1 {{field 'a': kind must be one of u|s|f|bytes (got 'q')}}
    bcir.binary.field @a { name = "a", offset_bits = 0 : i64, width_bits = 8 : i64, kind = "q", semantic = "" }
    bcir.binary.record @r { name = "r", fields = [@a], size_bits = 0 : i64 }
  }
}

// -----

// m5.field.end_overflow [R21] -- the end offset is signed 64-bit on the wire; the oracle admitted an end it could not hand the law rail (#762 review)
bcir.module @m {
  bcir.binary.format @f attributes { endianness = "little", alignment_bits = 8 : i64 } {
    // expected-error @+1 {{field 'a': offset_bits + width_bits exceeds signed 64-bit range}}
    bcir.binary.field @a { name = "a", offset_bits = 9223372036854775807 : i64, width_bits = 1 : i64, kind = "u", semantic = "" }
    bcir.binary.record @r { name = "r", fields = [@a], size_bits = 0 : i64 }
  }
}

// -----

// m5.record.overlap [R21]
bcir.module @m {
  bcir.binary.format @f attributes { endianness = "little", alignment_bits = 8 : i64 } {
    bcir.binary.field @b { name = "b", offset_bits = 0 : i64, width_bits = 32 : i64, kind = "u", semantic = "" }
    bcir.binary.field @c { name = "c", offset_bits = 16 : i64, width_bits = 32 : i64, kind = "u", semantic = "" }
    // expected-error @+1 {{record 'r': fields 'b' and 'c' overlap (bits [0, 32) and [16, 48))}}
    bcir.binary.record @r { name = "r", fields = [@b, @c], size_bits = 0 : i64 }
  }
}

// -----

// m5.record.exceeds_size [R21]
bcir.module @m {
  bcir.binary.format @f attributes { endianness = "little", alignment_bits = 8 : i64 } {
    bcir.binary.field @b { name = "b", offset_bits = 0 : i64, width_bits = 32 : i64, kind = "u", semantic = "" }
    // expected-error @+1 {{record 'r': field 'b' ends at bit 32, beyond the record's 16 bits}}
    bcir.binary.record @r { name = "r", fields = [@b], size_bits = 16 : i64 }
  }
}

// -----

// m5.record.dangling_field [R21] -- a record's fields are objects on the oracle; only a symbol reference can dangle
bcir.module @m {
  bcir.binary.format @f attributes { endianness = "little", alignment_bits = 8 : i64 } {
    bcir.binary.field @b { name = "b", offset_bits = 0 : i64, width_bits = 32 : i64, kind = "u", semantic = "" }
    // expected-error @+1 {{record 'r': field @ghost does not resolve to a bcir.binary.field}}
    bcir.binary.record @r { name = "r", fields = [@b, @ghost], size_bits = 0 : i64 }
  }
}

// -----

// m5.format.endianness_unknown [R21]
bcir.module @m {
  // expected-error @+1 {{format 'f': endianness must be one of little|big|le|be (got 'middle')}}
  bcir.binary.format @f attributes { endianness = "middle", alignment_bits = 8 : i64 } {
    bcir.binary.field @b { name = "b", offset_bits = 0 : i64, width_bits = 32 : i64, kind = "u", semantic = "" }
    bcir.binary.record @r { name = "r", fields = [@b], size_bits = 0 : i64 }
  }
}

// -----

// m5.format.alignment_zero [R21]
bcir.module @m {
  // expected-error @+1 {{format 'f': alignment_bits must be positive (got 0)}}
  bcir.binary.format @f attributes { endianness = "little", alignment_bits = 0 : i64 } {
    bcir.binary.field @b { name = "b", offset_bits = 0 : i64, width_bits = 32 : i64, kind = "u", semantic = "" }
    bcir.binary.record @r { name = "r", fields = [@b], size_bits = 0 : i64 }
  }
}

// -----

// m5.format.duplicate_record_name [R21] -- two records with distinct symbols and one name: the symbol table cannot see it (#762 review)
bcir.module @m {
  // expected-error @+1 {{format 'f': duplicate record name 'r'}}
  bcir.binary.format @f attributes { endianness = "little", alignment_bits = 8 : i64 } {
    bcir.binary.field @a { name = "a", offset_bits = 0 : i64, width_bits = 8 : i64, kind = "u", semantic = "" }
    bcir.binary.record @r { name = "r", fields = [@a], size_bits = 0 : i64 }
    bcir.binary.record @r2 { name = "r", fields = [@a], size_bits = 0 : i64 }
  }
}

// -----

// m5.stream.legal [legal]
bcir.module @m {
  bcir.event.stream @s { kind = "binary", encoding = "le", element_bits = 8 : i64, max_window = 64 : i64 }
}

// -----

// m5.stream.kind_unknown [R21]
bcir.module @m {
  // expected-error @+1 {{stream 's': kind must be one of text|binary|telemetry|packet|driver|token (got 'smoke')}}
  bcir.event.stream @s { kind = "smoke", encoding = "le", element_bits = 8 : i64, max_window = 64 : i64 }
}

// -----

// m5.stream.element_bits_zero [R21]
bcir.module @m {
  // expected-error @+1 {{stream 's': element_bits must be positive (got 0)}}
  bcir.event.stream @s { kind = "binary", encoding = "le", element_bits = 0 : i64, max_window = 64 : i64 }
}

// -----

// m5.stream.max_window_zero [R21]
bcir.module @m {
  // expected-error @+1 {{stream 's': max_window must be positive (got 0)}}
  bcir.event.stream @s { kind = "binary", encoding = "le", element_bits = 8 : i64, max_window = 0 : i64 }
}

// -----

// m5.fsm.legal [legal]
bcir.module @m {
  bcir.event.stream @src { kind = "token", encoding = "utf8", element_bits = 8 : i64, max_window = 64 : i64 }
  bcir.fsm.machine @fsm attributes { kind = "transducer", input_stream = @src, start_state = @s0 } {
    bcir.fsm.state @s0 { accepting = false, error = false }
    bcir.fsm.state @s1 { accepting = true, error = false }
    bcir.fsm.transition @t0 { from = @s0, to = @s1, on = "claim", guard = "", action = "" }
  }
}

// -----

// m5.fsm.state_accepting_and_error [R21]
bcir.module @m {
  bcir.event.stream @src { kind = "token", encoding = "utf8", element_bits = 8 : i64, max_window = 64 : i64 }
  bcir.fsm.machine @fsm attributes { kind = "transducer", input_stream = @src, start_state = @s0 } {
    // expected-error @+1 {{fsm state 's0': a state is accepting or an error, not both}}
    bcir.fsm.state @s0 { accepting = true, error = true }
  }
}

// -----

// m5.fsm.transition_to_unknown_state [R21]
bcir.module @m {
  bcir.event.stream @src { kind = "token", encoding = "utf8", element_bits = 8 : i64, max_window = 64 : i64 }
  bcir.fsm.machine @fsm attributes { kind = "transducer", input_stream = @src, start_state = @s0 } {
    bcir.fsm.state @s0 { accepting = false, error = false }
    // expected-error @+1 {{fsm transition 't0': @gone does not resolve to a bcir.fsm.state}}
    bcir.fsm.transition @t0 { from = @s0, to = @gone, on = "x", guard = "", action = "" }
  }
}

// -----

// m5.fsm.duplicate_transition [R21]
bcir.module @m {
  bcir.event.stream @src { kind = "token", encoding = "utf8", element_bits = 8 : i64, max_window = 64 : i64 }
  // expected-error @+1 {{fsm machine 'fsm': transition on 'x' from @s0 is declared twice}}
  bcir.fsm.machine @fsm attributes { kind = "transducer", input_stream = @src, start_state = @s0 } {
    bcir.fsm.state @s0 { accepting = false, error = false }
    bcir.fsm.transition @t0 { from = @s0, to = @s0, on = "x", guard = "", action = "" }
    bcir.fsm.transition @t1 { from = @s0, to = @s0, on = "x", guard = "", action = "" }
  }
}

// -----

// m5.fsm.unknown_start [R21]
bcir.module @m {
  bcir.event.stream @src { kind = "token", encoding = "utf8", element_bits = 8 : i64, max_window = 64 : i64 }
  // expected-error @+1 {{fsm machine 'fsm': start_state @nowhere does not name a bcir.fsm.state of this machine}}
  bcir.fsm.machine @fsm attributes { kind = "transducer", input_stream = @src, start_state = @nowhere } {
    bcir.fsm.state @s0 { accepting = false, error = false }
  }
}

// -----

// m5.grammar.legal [legal]
bcir.module @m {
  bcir.parse.grammar @g attributes { syntax = "ebnf", start_symbol = "claim" } {
    bcir.parse.token @IDENT { pattern = "[A-Za-z_][A-Za-z0-9_]*", skip = false, precedence = 0 : i32 }
    bcir.parse.token @INT { pattern = "[0-9]+", skip = false, precedence = 0 : i32 }
  }
}

// -----

// m5.grammar.empty_start [R21]
bcir.module @m {
  // expected-error @+1 {{grammar 'g': start_symbol must be non-empty}}
  bcir.parse.grammar @g attributes { syntax = "ebnf", start_symbol = "" } {
    bcir.parse.token @IDENT { pattern = "[A-Za-z_]+", skip = false, precedence = 0 : i32 }
  }
}

// -----

// m5.grammar.no_tokens [R21] -- the tokenless body is spelled as an empty block (`^bb0:`) on the law rail (#762 review)
bcir.module @m {
  // expected-error @+1 {{grammar 'g': at least one token rule is required (tokens must be non-empty)}}
  bcir.parse.grammar @g attributes { syntax = "ebnf", start_symbol = "claim" } {
  ^bb0:
  }
}

// -----

// m5.token.empty_pattern [R21]
bcir.module @m {
  bcir.parse.grammar @g attributes { syntax = "ebnf", start_symbol = "claim" } {
    // expected-error @+1 {{token rule 'T': pattern must be non-empty}}
    bcir.parse.token @T { pattern = "", skip = false, precedence = 0 : i32 }
  }
}

// -----

// m5.grammar.duplicate_token [R21]
bcir.module @m {
  // expected-error @+1 {{grammar 'g': duplicate token rule 'T'}}
  bcir.parse.grammar @g attributes { syntax = "ebnf", start_symbol = "claim" } {
    bcir.parse.token @T { pattern = "a", skip = false, precedence = 0 : i32 }
    bcir.parse.token @T { pattern = "b", skip = false, precedence = 0 : i32 }
  }
}

// -----

// conv.legal [legal]
bcir.module @m {
  bcir.gem.conv @cv { in_c = 2 : i64, in_h = 5 : i64, in_w = 5 : i64, out_c = 3 : i64, kh = 3 : i64, kw = 3 : i64, stride = 1 : i64, pad = 0 : i64, dtype = "f32", out_h = 3 : i64, out_w = 3 : i64, gemm_m = 9 : i64, gemm_n = 3 : i64, gemm_k = 18 : i64, strategy = "direct", tile_m = 9 : i64, tile_n = 3 : i64, tile_k = 18 : i64, loop_order = "ijk", compute_cost = 0 : i64, mem_cost = 0 : i64, bottleneck = 0 : i64, quant_bits = 0 : i32, acc_bound = 0 : i64 }
}

// -----

// conv.output_overflow [R22] -- the one-tile conv that wrapped its count to 0 in the GEM lowerer (row 13)
bcir.module @m {
  // expected-error @+1 {{conv: output element count exceeds signed 64-bit range}}
  bcir.gem.conv @cv { in_c = 1 : i64, in_h = 2147483648 : i64, in_w = 2147483648 : i64, out_c = 4 : i64, kh = 1 : i64, kw = 1 : i64, stride = 1 : i64, pad = 0 : i64, dtype = "f32", out_h = 2147483648 : i64, out_w = 2147483648 : i64, gemm_m = 4611686018427387904 : i64, gemm_n = 4 : i64, gemm_k = 1 : i64, strategy = "direct", tile_m = 4611686018427387904 : i64, tile_n = 4 : i64, tile_k = 1 : i64, loop_order = "ijk", compute_cost = 0 : i64, mem_cost = 0 : i64, bottleneck = 0 : i64, quant_bits = 0 : i32, acc_bound = 0 : i64 }
}

// -----

// conv.work_overflow [R22]
bcir.module @m {
  // expected-error @+1 {{conv: im2col work M*N*K exceeds signed 64-bit range}}
  bcir.gem.conv @cv { in_c = 16384 : i64, in_h = 1048576 : i64, in_w = 1048576 : i64, out_c = 1024 : i64, kh = 1 : i64, kw = 1 : i64, stride = 1 : i64, pad = 0 : i64, dtype = "f32", out_h = 1048576 : i64, out_w = 1048576 : i64, gemm_m = 1099511627776 : i64, gemm_n = 1024 : i64, gemm_k = 16384 : i64, strategy = "direct", tile_m = 1099511627776 : i64, tile_n = 1024 : i64, tile_k = 16384 : i64, loop_order = "ijk", compute_cost = 0 : i64, mem_cost = 0 : i64, bottleneck = 0 : i64, quant_bits = 0 : i32, acc_bound = 0 : i64 }
}

// -----

// conv.stride_zero [R22]
bcir.module @m {
  // expected-error @+1 {{conv: stride must be >= 1 (got 0)}}
  bcir.gem.conv @cv { in_c = 2 : i64, in_h = 5 : i64, in_w = 5 : i64, out_c = 3 : i64, kh = 3 : i64, kw = 3 : i64, stride = 0 : i64, pad = 0 : i64, dtype = "f32", out_h = 1 : i64, out_w = 1 : i64, gemm_m = 1 : i64, gemm_n = 3 : i64, gemm_k = 18 : i64, strategy = "direct", tile_m = 1 : i64, tile_n = 3 : i64, tile_k = 18 : i64, loop_order = "ijk", compute_cost = 0 : i64, mem_cost = 0 : i64, bottleneck = 0 : i64, quant_bits = 0 : i32, acc_bound = 0 : i64 }
}

// -----

// map.hbm_only [legal]
bcir.module @map {
  bcir.registry @RES {
    bcir.resource @r10 { rid = 10 : i32, domain_kind = #bcir.domain<hbm>, shape = array<i64: 8>, layout = #bcir.layout<soa>, align = 64 : i32 }
    bcir.resource @r12 { rid = 12 : i32, domain_kind = #bcir.domain<hbm>, shape = array<i64: 8>, layout = #bcir.layout<soa>, align = 64 : i32 }
  }
  bcir.phase @p0 { id = 0 : i32, deps = [] }
  bcir.claim @c1000 attributes { claim_id = 1000 : i32, phase = @p0, op = "map.add", reads = [@r10, @r10], writes = [@r12], count = 8 : i64, lane = #bcir.lane<u>, stride_class = #bcir.stride_class<unit>, stride_k = 1 : i32, offset = 0 : i64, domain = #bcir.domain<hbm>, hazard = #bcir.hazard<unique>, verify = #bcir.verify<bounds>, bounds = #bcir.bounds<strict> } { %i = bcir.index_range 0 to 8 step 1 }
}

// -----

// map.mmio_write_barriered [legal]
bcir.module @map {
  bcir.registry @RES {
    bcir.resource @r5 { rid = 5 : i32, domain_kind = #bcir.domain<mmio>, shape = array<i64: 1>, layout = #bcir.layout<soa>, align = 64 : i32 }
    bcir.resource @r10 { rid = 10 : i32, domain_kind = #bcir.domain<ram>, shape = array<i64: 8>, layout = #bcir.layout<soa>, align = 64 : i32 }
  }
  bcir.phase @p0 { id = 0 : i32, deps = [] }
  bcir.claim @c1000 attributes { claim_id = 1000 : i32, phase = @p0, op = "map.add", reads = [@r10], writes = [@r5], count = 1 : i64, lane = #bcir.lane<u>, stride_class = #bcir.stride_class<unit>, stride_k = 1 : i32, offset = 0 : i64, domain = #bcir.domain<mmio>, hazard = #bcir.hazard<barriered>, verify = #bcir.verify<bounds>, bounds = #bcir.bounds<strict>, is_volatile = true } { %i = bcir.index_range 0 to 1 step 1 }
}

// -----

// map.mmio_write_default_hazard [R3] -- both rails also report R5 (a volatile access needs an ordered hazard)
bcir.module @map {
  bcir.registry @RES {
    bcir.resource @r5 { rid = 5 : i32, domain_kind = #bcir.domain<mmio>, shape = array<i64: 1>, layout = #bcir.layout<soa>, align = 64 : i32 }
    bcir.resource @r10 { rid = 10 : i32, domain_kind = #bcir.domain<ram>, shape = array<i64: 8>, layout = #bcir.layout<soa>, align = 64 : i32 }
  }
  bcir.phase @p0 { id = 0 : i32, deps = [] }
  // expected-error @+2 {{R3: claim c1000 MMIO write to @r5 requires an atomic/barriered hazard}}
  // expected-error @+1 {{R5: claim c1000 volatile access requires an atomic/barriered hazard}}
  bcir.claim @c1000 attributes { claim_id = 1000 : i32, phase = @p0, op = "map.add", reads = [@r10], writes = [@r5], count = 1 : i64, lane = #bcir.lane<u>, stride_class = #bcir.stride_class<unit>, stride_k = 1 : i32, offset = 0 : i64, domain = #bcir.domain<mmio>, hazard = #bcir.hazard<unique>, verify = #bcir.verify<bounds>, bounds = #bcir.bounds<strict>, is_volatile = true } { %i = bcir.index_range 0 to 1 step 1 }
}

// -----

// rop.hbm_only [legal]
bcir.module @m {
  bcir.registry @RES {
    bcir.resource @r10 { rid = 10 : i32, domain_kind = #bcir.domain<hbm>, shape = array<i64: 8>, layout = #bcir.layout<soa>, align = 64 : i32 }
    bcir.resource @r12 { rid = 12 : i32, domain_kind = #bcir.domain<hbm>, shape = array<i64: 8>, layout = #bcir.layout<soa>, align = 64 : i32 }
  }
  bcir.phase @p0 { id = 0 : i32, deps = [] }
  bcir.claim @c1000 attributes { claim_id = 1000 : i32, phase = @p0, op = "rop.add", reads = [@r10], writes = [@r12], count = 8 : i64, lane = #bcir.lane<u>, stride_class = #bcir.stride_class<unit>, stride_k = 1 : i32, offset = 0 : i64, domain = #bcir.domain<hbm>, hazard = #bcir.hazard<unique>, verify = #bcir.verify<bounds>, bounds = #bcir.bounds<strict> } { %i = bcir.index_range 0 to 8 step 1 }
}

// -----

// rop.mmio_read_barriered [legal]
bcir.module @m {
  bcir.registry @RES {
    bcir.resource @r5 { rid = 5 : i32, domain_kind = #bcir.domain<mmio>, shape = array<i64: 1>, layout = #bcir.layout<soa>, align = 64 : i32 }
    bcir.resource @r12 { rid = 12 : i32, domain_kind = #bcir.domain<ram>, shape = array<i64: 8>, layout = #bcir.layout<soa>, align = 64 : i32 }
  }
  bcir.phase @p0 { id = 0 : i32, deps = [] }
  bcir.claim @c1000 attributes { claim_id = 1000 : i32, phase = @p0, op = "rop.rd", reads = [@r5], writes = [@r12], count = 1 : i64, lane = #bcir.lane<u>, stride_class = #bcir.stride_class<unit>, stride_k = 1 : i32, offset = 0 : i64, domain = #bcir.domain<mmio>, hazard = #bcir.hazard<barriered>, verify = #bcir.verify<bounds>, bounds = #bcir.bounds<strict>, is_volatile = true } { %i = bcir.index_range 0 to 1 step 1 }
}

// -----

// rop.mmio_read_default_hazard [R5]
bcir.module @m {
  bcir.registry @RES {
    bcir.resource @r5 { rid = 5 : i32, domain_kind = #bcir.domain<mmio>, shape = array<i64: 1>, layout = #bcir.layout<soa>, align = 64 : i32 }
    bcir.resource @r12 { rid = 12 : i32, domain_kind = #bcir.domain<ram>, shape = array<i64: 8>, layout = #bcir.layout<soa>, align = 64 : i32 }
  }
  bcir.phase @p0 { id = 0 : i32, deps = [] }
  // expected-error @+1 {{R5: claim c1000 volatile access requires an atomic/barriered hazard}}
  bcir.claim @c1000 attributes { claim_id = 1000 : i32, phase = @p0, op = "rop.rd", reads = [@r5], writes = [@r12], count = 1 : i64, lane = #bcir.lane<u>, stride_class = #bcir.stride_class<unit>, stride_k = 1 : i32, offset = 0 : i64, domain = #bcir.domain<mmio>, hazard = #bcir.hazard<unique>, verify = #bcir.verify<bounds>, bounds = #bcir.bounds<strict>, is_volatile = true } { %i = bcir.index_range 0 to 1 step 1 }
}
