#!/usr/bin/env python3
"""Generate docs/STATUS.md from the code -- the single source of truth for static inventories.

The repo changes too fast for hand-maintained numbers (the 580 vs 615 vs 631 / R17 vs R18 drift).
Everything here is computed from the tree, so prose never has to carry an exact count again:
just link to docs/STATUS.md. CI runs `--check` as a drift gate (committed == freshly generated).

    python tools/docs/gen_status.py            # print the generated STATUS.md
    python tools/docs/gen_status.py > docs/STATUS.md
    python tools/docs/gen_status.py --check     # exit 1 if docs/STATUS.md is stale
"""
from __future__ import annotations

import glob
import os
import re
import sys

ROOT = os.path.normpath(os.path.join(os.path.dirname(__file__), "..", ".."))


def _read(path: str) -> str:
    try:
        with open(os.path.join(ROOT, path), encoding="utf-8") as f:
            return f.read()
    except OSError:
        return ""


def _glob(pat: str) -> list[str]:
    return sorted(glob.glob(os.path.join(ROOT, pat)))


def python_tests() -> tuple[int, int]:
    files = _glob("bcir/tests/test_*.py")
    n = sum(len(re.findall(r"^def test_", _read(os.path.relpath(f, ROOT)), re.M)) for f in files)
    return n, len(files)


def ods_ops() -> int:
    ops: set[str] = set()
    for f in _glob("mlir/include/BCIR/*.td"):
        ops |= set(re.findall(r'BCIR_Op<"([a-z0-9._]+)"', _read(os.path.relpath(f, ROOT))))
    return len(ops)


def registered_passes() -> int:
    return _read("mlir/lib/BCIRPasses.cpp").count("registerPass")


def mlir_tests() -> tuple[int, int]:
    files = _glob("mlir/test/**/*.mlir") + _glob("mlir/test/*.mlir")
    files = sorted(set(files))
    neg = sum(_read(os.path.relpath(f, ROOT)).count("expected-error") for f in files)
    return len(files), neg


def runtime_c() -> list[str]:
    return [os.path.basename(f) for f in _glob("runtime/c/*.c") + _glob("runtime/c/*.h")]


def verifier_laws() -> list[tuple[str, bool]]:
    """R1..R23 with whether each has a negative `-verify-diagnostics` case in the law tests.

    Detected directly from the committed `mlir/test/passes/verify*.mlir` tree (no hand-listed
    exceptions): a law is "covered" iff its `Rn` tag appears in a negative case. All currently
    do, including R1 (`verify_laws.mlir`), R18 (`verify_callgraph.mlir`), the timing/lifetime
    laws R19/R20/R21 (`verify_timing_lifetime.mlir`), and the gem shape/dtype seam laws
    R22/R23 (`verify_shape_dtype.mlir`).
    """
    neg = "".join(_read(os.path.relpath(f, ROOT)) for f in _glob("mlir/test/passes/verify*.mlir"))
    return [(f"R{i}", bool(re.search(rf"\bR{i}\b", neg))) for i in range(1, 24)]


def channels() -> list[tuple[str, str]]:
    sys.path.insert(0, ROOT)
    try:
        from bcir.channels import CHANNELS  # noqa: PLC0415
        return sorted((c.name, c.kind) for c in CHANNELS.values())
    except Exception:  # noqa: BLE001 -- generator must never hard-fail
        return []


def render() -> str:
    ntests, nfiles = python_tests()
    ntd, nneg = mlir_tests()
    laws = verifier_laws()
    last_law = laws[-1][0]          # e.g. "R21" -- the law range is derived, never hard-coded
    chans = channels()
    kinds = sorted({k for _, k in chans})
    cfiles = runtime_c()

    L = []
    a = L.append
    a("# BCIR status (generated — do not edit by hand)\n")
    a("<!-- GENERATED by tools/docs/gen_status.py. Regenerate: `python tools/docs/gen_status.py >")
    a("     docs/STATUS.md`. CI drift gate: `python tools/docs/gen_status.py --check`. Prose should")
    a("     link here rather than hard-code counts (the 580/615/631 + R17/R18 drift this prevents). -->\n")
    a("| Metric | Value |")
    a("|---|---|")
    a(f"| Static Python `test_*` function inventory | **{ntests}** across {nfiles} files |")
    a(f"| Static MLIR ODS op-definition inventory (`mlir/include/BCIR/*.td`) | **{ods_ops()}** |")
    a(f"| Static registered-pass inventory | **{registered_passes()}** |")
    a(f"| Static MLIR fixture inventory (`mlir/test/`) | **{ntd}** files; {nneg} `expected-error` markers |")
    a(f"| Static runtime C source/header inventory (`runtime/c/`) | **{len(cfiles)}** files |")
    a(f"| Verifier-law negative-fixture tag inventory | **R1–{last_law}** ({sum(1 for _, ok in laws if ok)}/{len(laws)} present) |")
    a(f"| Registered hardware-channel inventory | **{len(chans)}** ({', '.join(kinds)}) |")
    a("")
    a(f"## Verifier-law negative-fixture inventory (R1–{last_law})\n")
    a("This is a static inventory, not evidence that the suite was executed. A check mark means the")
    a("law tag appears in a negative `-verify-diagnostics` fixture under")
    a("`mlir/test/passes/verify*.mlir`. R1 (RID uniqueness)")
    a("and R18 (call-graph integrity) are *additionally* construction-enforced on the oracle rail")
    a("(dict-keyed registry; `plan_composite` raises), so a malformed module can't even be built")
    a("there — but both still carry MLIR negative cases for hand-written IR (R1 in `verify_laws.mlir`,")
    a("R18 in `verify_callgraph.mlir`). R19/R20 (synchronous timing / clock-domain crossing) and R21")
    a("(pointer lifetime: use-after-free / double-free) ride **optional** claim metadata that defaults")
    a("to absent, so they are vacuous over the entire scalar/C subset (the non-disturbance invariant) —")
    a("their negative cases live in `verify_timing_lifetime.mlir`.\n")
    a("| " + " | ".join(law for law, _ in laws) + " |")
    a("|" + "---|" * len(laws))
    a("| " + " | ".join("✅" if ok else "—" for _, ok in laws) + " |")
    a("")
    a("## Hardware channel / target matrix\n")
    a("| Channel | Kind |")
    a("|---|---|")
    for name, kind in chans:
        a(f"| `{name}` | {kind} |")
    a("")
    a("## Runtime C components\n")
    a(", ".join(f"`{c}`" for c in cfiles))
    a("")
    return "\n".join(L) + "\n"


def main() -> int:
    out = render()
    if "--check" in sys.argv:
        committed = _read("docs/STATUS.md")
        if committed.strip() != out.strip():
            sys.stderr.write("docs/STATUS.md is STALE -- regenerate: "
                             "python tools/docs/gen_status.py > docs/STATUS.md\n")
            return 1
        sys.stderr.write("docs/STATUS.md is current.\n")
        return 0
    sys.stdout.write(out)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
