"""Frozen Q8 memory-tier table -> a C runtime artifact baked in with C23 `#embed`.

The K_BCIR cost algebra's memory-tier factors are *frozen* Q8 constants (256 ==
x1.0): per tier, a bandwidth factor and a latency factor vs DRAM. The single source
of truth is `bcir.kbcir.cost.MemoryHierarchy.default()` (the same table the C++
`-bcir-cost-model` mirrors in `tierForDomain`). This module freezes that table to a
little-endian binary blob and a generated C header so the deterministic C runtime can
consume it with **no parsing at startup**:

  * `#embed "q8_tiers.bin"` (ISO/IEC 9899:2023 6.10.3) bakes the blob straight into the
    translation unit when the toolchain supports it -- the frozen table *is* the bytes,
    no codegen-of-a-C-array, no drift between blob and array;
  * a generated fallback array (the identical bytes) keeps the header buildable on
    pre-`#embed` toolchains (clang < 19 / gcc < 15), selected by `__has_embed`.

The committed `runtime/c/{q8_tiers.bin,bcir_q8_tables.h}` are regenerated by
`python -m bcir.abi.q8_tables --emit`; a drift gate (CI + test_c23_runtime) keeps them
equal to a fresh emission, so the runtime's table can never silently diverge from the
oracle's.
"""

from __future__ import annotations

import os
import struct

from ..kbcir.cost import MemoryHierarchy, MemTier

# Each tier contributes two little-endian uint16 Q8 factors: {bw, lat} vs DRAM.
_BYTES_PER_TIER = 4
NTIERS = len(MemTier)


def q8_tiers() -> tuple[tuple[str, int, int], ...]:
    """The frozen table as `(tier_name, bw_q8, lat_q8)` in normative MemTier order."""
    h = MemoryHierarchy.default()
    rows = []
    for t in MemTier:
        tier = h.by_name(t.name)
        for v in (tier.bw_factor, tier.lat_factor):
            if not (0 <= v <= 0xFFFF):
                raise ValueError(f"Q8 factor {v} for {t.name} does not fit a uint16")
        rows.append((t.name, tier.bw_factor, tier.lat_factor))
    return tuple(rows)


def q8_tiers_blob() -> bytes:
    """The frozen table as little-endian uint16 pairs (bw, lat), MemTier order."""
    out = bytearray()
    for _name, bw, lat in q8_tiers():
        out += struct.pack("<HH", bw, lat)
    return bytes(out)


def _fallback_array(blob: bytes) -> str:
    rows = []
    for i in range(0, len(blob), _BYTES_PER_TIER):
        chunk = blob[i : i + _BYTES_PER_TIER]
        rows.append("  " + ", ".join(f"0x{b:02x}" for b in chunk) + ",")
    return "\n".join(rows)


def q8_tables_header(blob: bytes | None = None) -> str:
    """The generated C header: `#embed`-baked (guarded) or fallback array + accessors."""
    blob = q8_tiers_blob() if blob is None else blob
    rows = q8_tiers()
    legend = "; ".join(f"{name}={bw}/{lat}" for name, bw, lat in rows)
    return f"""/*===- bcir_q8_tables.h - frozen Q8 memory-tier factors (GENERATED) -------===
 *
 * The K_BCIR memory-tier Q8 factors {{bw, lat}} vs DRAM (256 == x1.0), baked into the
 * runtime. Source of truth: bcir/kbcir/cost.py MemoryHierarchy.default() (mirrored by
 * the C++ -bcir-cost-model tierForDomain). DO NOT EDIT -- regenerate with
 *   python -m bcir.abi.q8_tables --emit
 * (a drift gate keeps this == a fresh emission). MemTier order, {legend}.
 *
 * C23 #embed (6.10.3) bakes runtime/c/q8_tiers.bin directly when the toolchain
 * supports it; otherwise the identical fallback bytes below (selected by __has_embed).
 *===----------------------------------------------------------------------===*/
#ifndef BCIR_Q8_TABLES_H
#define BCIR_Q8_TABLES_H

#include <stdint.h>

#define BCIR_Q8_NTIERS {NTIERS}
#define BCIR_Q8_ONE 256  /* x1.0 in Q8 */

/* __has_embed must be probed in a NESTED #if: on a pre-#embed toolchain it is not a
 * defined macro, and `defined(__has_embed) && __has_embed(...)` would still try to
 * expand the right operand. The nested form leaves it unparsed when unsupported. */
#if defined(__has_embed)
#  if __has_embed("q8_tiers.bin")
#    define BCIR_Q8_EMBED 1
#  endif
#endif
#if defined(BCIR_Q8_EMBED) && BCIR_Q8_EMBED
static const unsigned char bcir_q8_tiers_blob[] = {{
#embed "q8_tiers.bin"
}};
#else
#define BCIR_Q8_EMBED 0
static const unsigned char bcir_q8_tiers_blob[] = {{
{_fallback_array(blob)}
}};
#endif

_Static_assert(sizeof(bcir_q8_tiers_blob) == BCIR_Q8_NTIERS * 4,
               "BCIR Q8 tier table must be NTIERS * {{bw,lat}} little-endian uint16");

/* MemTier ids (normative; match bcir.kbcir.cost.MemTier / BCIRAttrs.td). */
enum bcir_q8_tier {{
  BCIR_Q8_L1 = 0, BCIR_Q8_L2 = 1, BCIR_Q8_L3 = 2, BCIR_Q8_DRAM = 3,
  BCIR_Q8_HBM = 4, BCIR_Q8_CXL = 5, BCIR_Q8_SSD = 6
}};

static inline uint16_t bcir_q8_u16(const unsigned char *p) {{
  return (uint16_t)((uint16_t)p[0] | ((uint16_t)p[1] << 8));
}}
/* Bandwidth factor (lower = more bandwidth) and latency factor for a tier, Q8 vs DRAM. */
static inline uint16_t bcir_q8_tier_bw(int tier) {{
  return bcir_q8_u16(&bcir_q8_tiers_blob[(unsigned)tier * 4 + 0]);
}}
static inline uint16_t bcir_q8_tier_lat(int tier) {{
  return bcir_q8_u16(&bcir_q8_tiers_blob[(unsigned)tier * 4 + 2]);
}}

#endif /* BCIR_Q8_TABLES_H */
"""


_RUNTIME_C = os.path.join(os.path.dirname(__file__), "..", "..", "runtime", "c")
_BLOB_PATH = os.path.normpath(os.path.join(_RUNTIME_C, "q8_tiers.bin"))
_HEADER_PATH = os.path.normpath(os.path.join(_RUNTIME_C, "bcir_q8_tables.h"))


def emit_files() -> tuple[str, str]:
    """(Re)write the committed blob + header from the oracle's table. Returns paths."""
    blob = q8_tiers_blob()
    with open(_BLOB_PATH, "wb") as f:
        f.write(blob)
    with open(_HEADER_PATH, "w", encoding="utf-8") as f:
        f.write(q8_tables_header(blob))
    return _BLOB_PATH, _HEADER_PATH


def main(argv: list[str] | None = None) -> int:
    import argparse

    p = argparse.ArgumentParser(
        prog="bcir.abi.q8_tables", description="Freeze the Q8 memory-tier table to the C runtime"
    )
    p.add_argument(
        "--emit", action="store_true", help="(re)write runtime/c/q8_tiers.bin + bcir_q8_tables.h"
    )
    args = p.parse_args(argv)
    if args.emit:
        blob_path, hdr_path = emit_files()
        print(f"[q8] wrote {blob_path} ({len(q8_tiers_blob())} bytes) + {hdr_path}")
        return 0
    for name, bw, lat in q8_tiers():
        print(f"{name:5} bw={bw:5} lat={lat}")
    return 0


if __name__ == "__main__":
    import sys

    sys.exit(main())
