#!/usr/bin/env bash
# per_plan: X.691 plan-driven PER decoder: strict-warning and freestanding build (#per)
#
# One section of tools/c/check_runtime.sh, run against binaries built elsewhere: the gate compiles
# them its own way and calls this script; the CMake project builds them from runtime/manifest.json
# and runs this script as the `c-section-per_plan` CTest entry. The body is the gate's section text
# moved here (BUILD-2, docs/BCIR_BUILD_ROADMAP.md), so the two run one text, and
# tools/build/section_parity.py holds the two builds' outputs byte-identical. The binaries are the
# manifest variants test_per_plan_O0 and test_per_plan_O3: the twin's harness with its whole
# library closure rebuilt at -O0 and at -O3, whose answers must not depend on the optimiser.
#
#   usage: per_plan.sh <test_per_plan_O0> <test_per_plan_O3>
set -uo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../../.." && pwd)"
C="${ROOT}/runtime/c"
PYTHON="${PYTHON:-python3}"
export PYTHONPATH="${ROOT}${PYTHONPATH:+:${PYTHONPATH}}"
[ $# -eq 2 ] || { echo "usage: per_plan.sh <test_per_plan_O0> <test_per_plan_O3>" >&2; exit 2; }
abs() { printf '%s/%s\n' "$(cd "$(dirname "$1")" && pwd)" "$(basename "$1")"; }
O0="$(abs "$1")"; [ -x "${O0}" ] || { echo "  FAIL: O0: ${O0} is not an executable variant"; exit 2; }
O3="$(abs "$2")"; [ -x "${O3}" ] || { echo "  FAIL: O3: ${O3} is not an executable variant"; exit 2; }
tmp="$(mktemp -d)"; trap 'rm -rf "${tmp}"' EXIT

# X.696 OER decoder (#oer, ASN.1 build-out phase D): the encoding rule with the best decode
# cost -- octet-aligned throughout, most fields fixed-width words a target loads directly --
# and therefore the one a driver-side or DMA-fed path actually wants. It is SCHEMA-DIRECTED
# because 6.2 leaves no choice: "without knowledge of the type of the value encoded, it is
# not possible to determine the structure of the encoding". The dual-rail differential lives
# in bcir/tests/test_c_oer.py; what is checked here is the usual discipline plus -O0 == -O3,
# which earns its place because the decoder sign-extends by hand and compares widths against
# attacker-supplied lengths.
# X.691 PER, decoded against a PLAN (#per, ASN.1 build-out phase H). 6.2's NOTE is why this
# has to be plan-driven: PER "does not include the identifier of the type being encoded" and
# "the abstract syntax is required in order to decode" -- no tags, no lengths except where a
# clause asks, fields at odd bit widths, so there is no schema-free structural pass at all.
# 7.2 bars the schema-FREE decode and says nothing against this one.
#
# The corpus is generated by BCIR's OWN PER encoder and read back by the C twin. Both variants
# are covered, because ALIGNED and UNALIGNED differ at every field boundary and a decoder
# correct on one can be wrong on the other in a way no single-variant corpus would show.
#
# WHAT THIS GATE DOES AND DOES NOT PROVE. The -O0/-O3 comparison below is a MISCOMPILATION
# check and nothing more: both columns come from the same decoder, so a decoder that is wrong
# about a rule agrees with itself perfectly. This gate once carried a comment calling that a
# "real differential", and two defects lived behind the claim -- a mid-octet string reported at
# the octet containing it, and 16.6's short string refused in ALIGNED PER. The comparison
# against what the encoder actually encoded lives in bcir/tests/test_c_per_plan.py, which
# decodes the same records and checks every field VALUE, locating each string by its reported
# bit offset. Keep that file in mind before trusting this one about correctness.
"${PYTHON}" - <<'PERPY' > "${tmp}/per_cases.txt"
import sys
sys.path.insert(0, ".")
from bcir.asn1.constraints import Size, ValueRange
from bcir.asn1.per import PerVariant, encode_per
from bcir.asn1.schema import Component, Primitive, Sequence
from bcir.asn1.tags import Universal

byte = Primitive(Universal.INTEGER, "INTEGER", constraint=ValueRange(0, 255))
word = Primitive(Universal.INTEGER, "INTEGER", constraint=ValueRange(0, 65535))
flag = Primitive(Universal.BOOLEAN, "BOOLEAN")
text = Primitive(Universal.OCTET_STRING, "OCTET STRING", constraint=Size(ValueRange(3, 3)))

# kind:bounds:lb:ub:fixed:optional -- every property bcir_per_field carries.
PLAN = "0:2:0:255:0:0,1:0:0:0:0:0,3:0:0:0:3:0"
record = Sequence((Component("id", byte), Component("flag", flag),
                   Component("name", text)), name="R")
for variant in (PerVariant.UNALIGNED, PerVariant.ALIGNED):
    aligned = 1 if variant is PerVariant.ALIGNED else 0
    for ident in (0, 1, 42, 254, 255):
        for truth in (True, False):
            raw = encode_per(record, {"id": ident, "flag": truth, "name": b"abc"},
                             variant=variant)
            print(f"sequence {raw.hex()} {aligned} 0 {PLAN}")

# A two-field record whose first component is optional, so 18.2's bit-map is exercised in
# both of its states rather than only in the one a happy path reaches.
opt = Sequence((Component("id", word, optional=True), Component("flag", flag)), name="O")
OPLAN = "0:2:0:65535:0:1,1:0:0:0:0:0"
for variant in (PerVariant.UNALIGNED, PerVariant.ALIGNED):
    aligned = 1 if variant is PerVariant.ALIGNED else 0
    for value in ({"flag": True}, {"id": 7, "flag": False}, {"id": 65535, "flag": True}):
        raw = encode_per(opt, value, variant=variant)
        print(f"sequence {raw.hex()} {aligned} 0 {OPLAN}")

# 16.6: a string of two octets or fewer is placed with NO alignment in EITHER variant, so it
# begins at bit 1 here. The twin refused exactly this shape in ALIGNED PER until the sweep,
# and no corpus reached it -- every other record above has a string of three octets.
short = Primitive(Universal.OCTET_STRING, "OCTET STRING", constraint=Size(ValueRange(2, 2)))
brief = Sequence((Component("flag", flag), Component("s", short)), name="S")
SPLAN = "1:0:0:0:0:0,3:0:0:0:2:0"
for variant in (PerVariant.UNALIGNED, PerVariant.ALIGNED):
    aligned = 1 if variant is PerVariant.ALIGNED else 0
    raw = encode_per(brief, {"flag": True, "s": b"hi"}, variant=variant)
    print(f"sequence {raw.hex()} {aligned} 0 {SPLAN}")

# Truncation and refusal: every prefix of a valid encoding, plus the 18.1 extension bit.
raw = encode_per(record, {"id": 42, "flag": True, "name": b"abc"},
                 variant=PerVariant.UNALIGNED).hex()
for cut in range(0, len(raw) - 1, 2):
    print(f"sequence {raw[:cut]} 0 0 {PLAN}")
print(f"sequence 80{raw} 0 1 {PLAN}")
PERPY
"${O0}" < "${tmp}/per_cases.txt" > "${tmp}/per_O0.txt"
"${O3}" < "${tmp}/per_cases.txt" > "${tmp}/per_O3.txt"
if cmp -s "${tmp}/per_O0.txt" "${tmp}/per_O3.txt"; then
  cases=$(wc -l < "${tmp}/per_cases.txt")
  # A corpus that decoded nothing would compare equal too, so the gate checks that the
  # differential actually produced answers rather than a column of refusals.
  oks=$(grep -c '^OK' "${tmp}/per_O0.txt" || true)
  if [ "${oks}" -lt 20 ]; then
    echo "  FAIL: only ${oks} of ${cases} PER cases decoded; the corpus is not exercising the decoder"
    exit 1
  fi
  echo "  PASS X.691 plan-driven PER twin (freestanding, -Werror, -O0 == -O3 over ${cases} cases, ${oks} decoded)"
else
  echo "  FAIL: PER decoder differs between -O0 and -O3"; exit 1
fi
