/* GENERATED by `python -m bcir.signal_table --emit` from bcir/signal_registry.py.
 * Do not edit: tools/c/check_runtime.sh and bcir/tests/test_signal_table.py refuse a copy
 * that differs from the generator. Version zero (docs/kernel/TELEMETRY_ENVELOPE_ABI.md): no
 * compatibility promise until UART and virtio-blk traces revise the row. */
#ifndef BCIR_SIGNAL_TABLE_H
#define BCIR_SIGNAL_TABLE_H

#include <stdint.h>

#define BCIR_SIGNAL_TABLE_VERSION 0u
#define BCIR_SIGNAL_ROW_SIZE 64u
#define BCIR_SIGNAL_NAME_WIDTH 40u
#define BCIR_SIGNAL_COUNT 15u

/* The ID-range policy. */
#define BCIR_SIGNAL_ID_UNASSIGNED 0x00000000u
#define BCIR_SIGNAL_ID_BCIR_FIRST 0x00000001u
#define BCIR_SIGNAL_ID_BCIR_LAST 0x0000FFFFu
#define BCIR_SIGNAL_ID_VENDOR_FIRST 0x00010000u
#define BCIR_SIGNAL_ID_VENDOR_LAST 0x7FFFFFFFu
#define BCIR_SIGNAL_ID_DEVICE_FIRST 0x80000000u
#define BCIR_SIGNAL_ID_DEVICE_LAST 0xFFFFFFFEu
#define BCIR_SIGNAL_ID_RESERVED 0xFFFFFFFFu
#define BCIR_SIGNAL_COST_DIM_NONE 0xFFu
#define BCIR_SIGNAL_FLAG_MONOTONIC 0x01u

enum bcir_signal_unit {
  BCIR_SIGNAL_UNIT_NONE = 0,
  BCIR_SIGNAL_UNIT_PERCENT = 1,
  BCIR_SIGNAL_UNIT_MILLICELSIUS = 2,
  BCIR_SIGNAL_UNIT_MICROJOULE = 3,
  BCIR_SIGNAL_UNIT_MILLIWATT = 4,
  BCIR_SIGNAL_UNIT_MICROWATT = 5,
  BCIR_SIGNAL_UNIT_KHZ = 6,
  BCIR_SIGNAL_UNIT_BYTES = 7,
  BCIR_SIGNAL_UNIT_BYTES_PER_SECOND = 8,
  BCIR_SIGNAL_UNIT_BITMASK = 9,
  BCIR_SIGNAL_UNIT_COUNT = 10,
  BCIR_SIGNAL_UNIT_RATIO_MILLI = 11,
};
enum bcir_signal_kind { BCIR_SIGNAL_GAUGE = 0, BCIR_SIGNAL_COUNTER = 1 };
enum bcir_signal_temporality {
  BCIR_SIGNAL_UNSPECIFIED = 0,
  BCIR_SIGNAL_DELTA = 1,
  BCIR_SIGNAL_CUMULATIVE = 2,
};
enum bcir_signal_sampling {
  BCIR_SIGNAL_POLLED = 0,
  BCIR_SIGNAL_STREAMED = 1,
  BCIR_SIGNAL_EVENT_DRIVEN = 2,
};
enum bcir_signal_provenance {
  BCIR_SIGNAL_MEASURED = 0,
  BCIR_SIGNAL_MODELED = 1,
  BCIR_SIGNAL_SIMULATED = 2,
};

typedef struct bcir_signal_def {
  uint32_t id;
  uint8_t unit, kind, temporality, flags, sampling, provenance, cost_dim;
  uint64_t min_interval_ns;
  char name[BCIR_SIGNAL_NAME_WIDTH];
} bcir_signal_def;

/* Rows in strictly ascending ID order (a consumer may binary-search them). */
static const bcir_signal_def BCIR_SIGNAL_TABLE[BCIR_SIGNAL_COUNT] = {
    {1u, 1u, 0u, 0u, 0u, 0u, 0u, 5u, 0u, "thermal.pressure"},
    {2u, 2u, 0u, 0u, 0u, 0u, 0u, 5u, 0u, "thermal.die_millicelsius"},
    {3u, 3u, 1u, 2u, 1u, 0u, 0u, 6u, 0u, "power.rapl_energy_uj"},
    {4u, 6u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, "compute.cpu_nominal_khz"},
    {5u, 7u, 0u, 0u, 0u, 0u, 0u, 1u, 0u, "memory.cache_l1_bytes"},
    {6u, 7u, 0u, 0u, 0u, 0u, 0u, 1u, 0u, "memory.cache_l2_bytes"},
    {7u, 7u, 0u, 0u, 0u, 0u, 0u, 1u, 0u, "memory.cache_l3_bytes"},
    {8u, 10u, 0u, 0u, 0u, 2u, 0u, 0u, 0u, "compute.pmu_available"},
    {9u, 3u, 1u, 2u, 1u, 1u, 0u, 6u, 0u, "power.gpu_energy_uj"},
    {10u, 4u, 0u, 0u, 0u, 0u, 0u, 6u, 0u, "power.bmc_node_milliwatt"},
    {11u, 8u, 0u, 0u, 0u, 1u, 0u, 1u, 0u, "memory.bandwidth_bytes_per_s"},
    {12u, 7u, 1u, 2u, 1u, 1u, 0u, 2u, 0u, "fabric.interconnect_bytes"},
    {13u, 9u, 0u, 0u, 0u, 2u, 0u, 10u, 0u, "contention.throttle_state"},
    {14u, 10u, 0u, 0u, 0u, 2u, 0u, 7u, 0u, "reliability.ecc_rul"},
    {15u, 5u, 0u, 0u, 0u, 0u, 0u, 6u, 0u, "power.hwmon_microwatt"},
};

#endif /* BCIR_SIGNAL_TABLE_H */
