"""The ITS study's native half: generated C codecs for the security envelope, timed.

`its_security` settles the SIZE question on the oracle. Runtime and memory cannot be settled
there -- a Python encoder measures Python -- so this module compiles the two envelope modules
to C with `cgen` and drives every codec over the same four envelopes:

* the transcription (`ITS-SecuredMessage-V111`) under the V1.1.1 byte rule, COER and UPER --
  ONE C struct per envelope, three encodings of it, so a difference in cost is a difference
  of encoding rule;
* the TMSAO schema under COER (its rule-neutral instance, `SecuredMessage`) and UPER (its PER
  instance, `SecuredMessagePer`) -- each rule on the instance of the schema shaped for it.

Every codec is generated by the same compiler from the same ASN.1, so "binary" here is not a
weaker or stronger implementation than "ASN.1": it is the V1.1.1 byte rule, compiled exactly
as the ASN.1 rules are. That is the controlled comparison the 2015 study could not make --
its binary codec was hand-written and its ASN.1 codec a table-driven library.

**Parity before timing.** `parity()` must hold before `bench()` means anything: every
generated encoder writes the oracle's octets for every envelope, and every generated decoder
reads the oracle's octets back to the very value the encoder started from.

**What a timing row carries.** Each codec's encode and decode are timed in interleaved
rounds against one floor measured in the same run: `memcpy` of the encoding's own length,
the least work any encoder (write N octets) or decoder (read N octets) can do on the envelope.
A codec's ratio to that floor is what transfers between hosts; the nanoseconds do not.
"""

from __future__ import annotations

import os
import shutil
import subprocess
import tempfile
from dataclasses import dataclass

from .tags import Asn1Error

#: (harness codec name, model, rule name, root) for every generated codec, in report order.
CODECS = (
    ("v111", "transcription", "v111"),
    ("coer", "transcription", "coer"),
    ("uper", "transcription", "uper"),
    ("tmsao-coer", "tmsao", "coer"),
    ("tmsao-uper", "tmsao-per", "uper"),
)

#: Statuses, as `cgen` numbers them.
STATUS = {0: "OK", 1: "SPACE", 2: "TRUNC", 3: "MALFORMED", 4: "VALUE", 5: "LIMIT"}


def sources():
    """`{filename: text}` for both generated codecs and the harness driver."""
    from . import its_security as its
    from .cgen import COER, UPER, ValueWriter, generate

    v_types = its.transcription().module.types
    t_types = its.tmsao().module.types
    v = generate(
        v_types,
        ["SecuredMessage"],
        prefix="itsv_",
        rules=[its.v111_rule(), COER, UPER],
        equality=True,
    )
    t = generate(
        t_types,
        ["SecuredMessage", "SecuredMessagePer"],
        prefix="itst_",
        rules=[COER, UPER],
        equality=True,
    )

    from .cgen import CModel

    vw = ValueWriter(CModel(v_types, ["SecuredMessage"], "itsv_"))
    tw = ValueWriter(CModel(t_types, ["SecuredMessage", "SecuredMessagePer"], "itst_"))
    for i, (profile, value) in enumerate(its.envelopes().items()):
        vw.define(f"itsv_env{i}", "SecuredMessage", value)
        tw.define(f"itst_env{i}", "SecuredMessage", its.to_tmsao(value))
        tw.define(f"itst_penv{i}", "SecuredMessagePer", its.to_tmsao(value))
    values = "".join(vw.decls) + "".join(tw.decls)
    return {
        v.header_name: v.header,
        "itsv_codec.c": v.source,
        t.header_name: t.header,
        "itst_codec.c": t.source,
        "its_harness.c": _HARNESS.replace("@VALUES@", values),
    }


_HARNESS = r"""
/* its_harness.c -- drives the generated ITS envelope codecs (bcir/asn1/its_native.py).
 *
 *   enc <codec> <i>                encode envelope i: OK <hex> | ERR <status>
 *   dec <codec> <hex>              decode: OK <envelope index or -1> <arena octets> | ERR <s>
 *   bench <rounds> <iters>         time every codec on every envelope, interleaved
 *   cycle                          encode a cyclic value under every codec: OK <statuses>
 *   stack <codec> <i> <op>         stack high-water of one encode (op 0) or decode (op 1), in
 *                                  octets, on a thread whose painted stack is scanned after
 */
#define _POSIX_C_SOURCE 200809L
#include <pthread.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>

#include "itsv_codec.h"
#include "itst_codec.h"

@VALUES@

#define N_ENV 4
static const itsv_SecuredMessage *const V[N_ENV] = {&itsv_env0, &itsv_env1, &itsv_env2, &itsv_env3};
static const itst_SecuredMessage *const T[N_ENV] = {&itst_env0, &itst_env1, &itst_env2, &itst_env3};
static const itst_SecuredMessagePer *const TP[N_ENV] = {&itst_penv0, &itst_penv1, &itst_penv2,
                                                        &itst_penv3};
/* The value codec `c` encodes: the transcription's for 0-2, then the TMSAO instances. */
static const void *SRC(int c, int e) {
  return c < 3 ? (const void *)V[e] : c == 3 ? (const void *)T[e] : (const void *)TP[e];
}

static uint8_t arena_mem[1 << 16];

static int encode(const char *codec, int i, uint8_t *out, size_t cap, size_t *len) {
  if (!strcmp(codec, "v111")) return itsv_v111_encode_SecuredMessage(V[i], out, cap, len);
  if (!strcmp(codec, "coer")) return itsv_coer_encode_SecuredMessage(V[i], out, cap, len);
  if (!strcmp(codec, "uper")) return itsv_uper_encode_SecuredMessage(V[i], out, cap, len);
  if (!strcmp(codec, "tmsao-coer")) return itst_coer_encode_SecuredMessage(T[i], out, cap, len);
  if (!strcmp(codec, "tmsao-uper")) return itst_uper_encode_SecuredMessagePer(TP[i], out, cap, len);
  return -1;
}

/* Decode `in`, report which static envelope (if any) the value equals, and re-encode the
 * value with the same codec into `re` -- a canonical-only decoder accepts exactly the octets
 * its encoder writes, so a differential can hold the two to each other. */
static int decode(const char *codec, const uint8_t *in, size_t len, int *match, size_t *used,
                  uint8_t *re, size_t re_cap, size_t *re_len) {
  int st, i;
  itsv_arena av;
  itst_arena at;
  itsv_SecuredMessage v;
  itst_SecuredMessage t;
  itst_SecuredMessagePer tp;
  av.base = arena_mem; av.cap = sizeof(arena_mem); av.used = 0;
  at.base = arena_mem; at.cap = sizeof(arena_mem); at.used = 0;
  *match = -1;
  *re_len = 0;
  if (!strcmp(codec, "v111") || !strcmp(codec, "coer") || !strcmp(codec, "uper")) {
    if (!strcmp(codec, "v111")) st = itsv_v111_decode_SecuredMessage(in, len, &v, &av);
    else if (!strcmp(codec, "coer")) st = itsv_coer_decode_SecuredMessage(in, len, &v, &av);
    else st = itsv_uper_decode_SecuredMessage(in, len, &v, &av);
    *used = av.used;
    if (st != 0) return st;
    for (i = 0; i < N_ENV; i++) if (itsv_eq_SecuredMessage(&v, V[i])) { *match = i; break; }
    if (!strcmp(codec, "v111")) return 16 + itsv_v111_encode_SecuredMessage(&v, re, re_cap, re_len);
    if (!strcmp(codec, "coer")) return 16 + itsv_coer_encode_SecuredMessage(&v, re, re_cap, re_len);
    return 16 + itsv_uper_encode_SecuredMessage(&v, re, re_cap, re_len);
  }
  if (!strcmp(codec, "tmsao-coer")) {
    st = itst_coer_decode_SecuredMessage(in, len, &t, &at);
    *used = at.used;
    if (st != 0) return st;
    for (i = 0; i < N_ENV; i++) if (itst_eq_SecuredMessage(&t, T[i])) { *match = i; break; }
    return 16 + itst_coer_encode_SecuredMessage(&t, re, re_cap, re_len);
  }
  if (strcmp(codec, "tmsao-uper")) return -1;
  st = itst_uper_decode_SecuredMessagePer(in, len, &tp, &at);
  *used = at.used;
  if (st != 0) return st;
  for (i = 0; i < N_ENV; i++) if (itst_eq_SecuredMessagePer(&tp, TP[i])) { *match = i; break; }
  return 16 + itst_uper_encode_SecuredMessagePer(&tp, re, re_cap, re_len);
}

/* Two hex digits per octet, nothing else. `sscanf("%2x")` was the parser here, and it reads ONE
 * digit before a NUL (then `s += 2` stepped past the string's end), a sign, or a "0x" prefix:
 * three inputs the harness then decoded as if they were octets. */
static int nibble(char c) {
  if (c >= '0' && c <= '9') return c - '0';
  if (c >= 'a' && c <= 'f') return c - 'a' + 10;
  if (c >= 'A' && c <= 'F') return c - 'A' + 10;
  return -1;
}

static int unhex(const char *s, uint8_t *out, size_t cap, size_t *n) {
  size_t k = 0;
  while (s[0] && s[0] != '\n') {
    int hi = nibble(s[0]), lo = hi < 0 ? -1 : nibble(s[1]);
    if (lo < 0 || k >= cap) return -1;
    out[k++] = (uint8_t)(hi << 4 | lo);
    s += 2;
  }
  *n = k;
  return 0;
}

static uint64_t now_ns(void) {
  struct timespec ts;
  clock_gettime(CLOCK_MONOTONIC, &ts);
  return (uint64_t)ts.tv_sec * 1000000000u + (uint64_t)ts.tv_nsec;
}

static int cmp_u64(const void *a, const void *b) {
  uint64_t x = *(const uint64_t *)a, y = *(const uint64_t *)b;
  return x < y ? -1 : x > y;
}

static const char *const CODECS[] = {"v111", "coer", "uper", "tmsao-coer", "tmsao-uper"};
#define N_CODECS 5

/* Typed entry points, so the timed loop calls the codec directly rather than through the
 * name dispatch `encode`/`decode` use. */
typedef int (*enc_fn)(const void *, uint8_t *, size_t, size_t *);
static int e0(const void *v, uint8_t *o, size_t c, size_t *l) { return itsv_v111_encode_SecuredMessage(v, o, c, l); }
static int e1(const void *v, uint8_t *o, size_t c, size_t *l) { return itsv_coer_encode_SecuredMessage(v, o, c, l); }
static int e2(const void *v, uint8_t *o, size_t c, size_t *l) { return itsv_uper_encode_SecuredMessage(v, o, c, l); }
static int e3(const void *v, uint8_t *o, size_t c, size_t *l) { return itst_coer_encode_SecuredMessage(v, o, c, l); }
static int e4(const void *v, uint8_t *o, size_t c, size_t *l) { return itst_uper_encode_SecuredMessagePer(v, o, c, l); }
typedef int (*dec_fn)(const uint8_t *, size_t, void *, void *);
static int d0(const uint8_t *i, size_t n, void *v, void *a) { return itsv_v111_decode_SecuredMessage(i, n, v, a); }
static int d1(const uint8_t *i, size_t n, void *v, void *a) { return itsv_coer_decode_SecuredMessage(i, n, v, a); }
static int d2(const uint8_t *i, size_t n, void *v, void *a) { return itsv_uper_decode_SecuredMessage(i, n, v, a); }
static int d3(const uint8_t *i, size_t n, void *v, void *a) { return itst_coer_decode_SecuredMessage(i, n, v, a); }
static int d4(const uint8_t *i, size_t n, void *v, void *a) { return itst_uper_decode_SecuredMessagePer(i, n, v, a); }
static const enc_fn ENC[N_CODECS] = {e0, e1, e2, e3, e4};
static const dec_fn DEC[N_CODECS] = {d0, d1, d2, d3, d4};

static volatile uint64_t sink;

static void bench(long rounds, long iters) {
  /* samples[codec][env][op][round]; op 0 encode, 1 decode, 2 the memcpy floor */
  static uint64_t samples[N_CODECS][N_ENV][3][512];
  static uint8_t enc[N_CODECS][N_ENV][512];
  static size_t enc_len[N_CODECS][N_ENV];
  static uint8_t out[512], copy[512];
  static union { itsv_SecuredMessage v; itst_SecuredMessage t; itst_SecuredMessagePer p; } value;
  long r, it;
  int c, e, op;
  if (rounds > 512) rounds = 512;
  for (c = 0; c < N_CODECS; c++)
    for (e = 0; e < N_ENV; e++) {
      const void *src = SRC(c, e);
      itsv_arena av;
      itst_arena at;
      size_t relen = 0;
      if (ENC[c](src, enc[c][e], sizeof(enc[c][e]), &enc_len[c][e]) != 0) {
        printf("ERR bench-encode %s %d\n", CODECS[c], e);
        return;
      }
      /* Time only what works: every case decodes, and re-encodes to its own octets, once
       * before any clock starts -- a refused decode is fast, and timing it would report the
       * refusal as the codec's speed. */
      av.base = arena_mem; av.cap = sizeof(arena_mem); av.used = 0;
      at.base = arena_mem; at.cap = sizeof(arena_mem); at.used = 0;
      if (DEC[c](enc[c][e], enc_len[c][e], &value, c < 3 ? (void *)&av : (void *)&at) != 0 ||
          ENC[c](&value, out, sizeof(out), &relen) != 0 || relen != enc_len[c][e] ||
          memcmp(out, enc[c][e], relen) != 0) {
        printf("ERR bench-decode %s %d\n", CODECS[c], e);
        return;
      }
    }
  for (r = 0; r < rounds; r++)
    for (c = 0; c < N_CODECS; c++)
      for (e = 0; e < N_ENV; e++) {
        const void *src = SRC(c, e);
        for (op = 0; op < 3; op++) {
          uint64_t t0, t1;
          size_t len = 0;
          t0 = now_ns();
          for (it = 0; it < iters; it++) {
            if (op == 0) {
              ENC[c](src, out, sizeof(out), &len);
              sink += len + out[len ? len - 1 : 0];
            } else if (op == 1) {
              /* Each family decodes into its own arena type: the two are laid out alike, but
               * reading one through the other's type would be an aliasing violation. */
              itsv_arena av;
              itst_arena at;
              av.base = arena_mem; av.cap = sizeof(arena_mem); av.used = 0;
              at.base = arena_mem; at.cap = sizeof(arena_mem); at.used = 0;
              sink += (uint64_t)DEC[c](enc[c][e], enc_len[c][e], &value,
                                       c < 3 ? (void *)&av : (void *)&at) + av.used + at.used;
            } else {
              memcpy(copy, enc[c][e], enc_len[c][e]);
              __asm__ __volatile__("" : : "r"(copy) : "memory");
              sink += copy[enc_len[c][e] - 1];
            }
          }
          t1 = now_ns();
          samples[c][e][op][r] = (t1 - t0);
        }
      }
  for (c = 0; c < N_CODECS; c++)
    for (e = 0; e < N_ENV; e++)
      for (op = 0; op < 3; op++) {
        qsort(samples[c][e][op], (size_t)rounds, sizeof(uint64_t), cmp_u64);
        printf("time %s %d %s %zu %.3f %.3f %.3f\n", CODECS[c], e,
               op == 0 ? "encode" : op == 1 ? "decode" : "floor", enc_len[c][e],
               (double)samples[c][e][op][rounds / 4] / (double)iters,
               (double)samples[c][e][op][rounds / 2] / (double)iters,
               (double)samples[c][e][op][(3 * rounds) / 4] / (double)iters);
      }
}

/* --- stack high-water ----------------------------------------------------------------------
 * The codec runs once on a thread whose stack the harness owns. Thread start-up dirties stack
 * of its own, so the thread re-paints everything below its entry frame (keeping a margin for
 * the memset's own frame) and the codec runs into fresh paint; afterwards the lowest
 * overwritten octet is the deepest it reached, measured from the entry frame. A thread doing
 * nothing past the paint is the baseline subtracted, so what remains is the codec's frames. */
typedef struct { int codec, env, op, st; uint8_t *base; uintptr_t entry; } stack_job;
#define STACK_PAINT 0xA5u
#define STACK_SIZE ((size_t)1 << 20)
/* Past the x86-64 red zone (128 octets) with room for this function's own frame. The paint is
 * a plain loop -- a memset would run its own frame inside the margin -- so the codec's frames
 * are measured down to within STACK_MARGIN of the entry frame. */
#define STACK_MARGIN 192u

static void paint_below(stack_job *j) {
  volatile uint8_t marker = 0;
  volatile uint8_t *p = (volatile uint8_t *)j->base;
  uintptr_t stop = (uintptr_t)&marker - STACK_MARGIN;
  j->entry = (uintptr_t)&marker;
  while ((uintptr_t)p < stop) *p++ = (uint8_t)STACK_PAINT;
}

static void *stack_run(void *p) {
  stack_job *j = (stack_job *)p;
  static uint8_t out_buf[512];
  static union { itsv_SecuredMessage v; itst_SecuredMessage t; itst_SecuredMessagePer p; } value;
  static uint8_t enc_buf[512];
  size_t len = 0;
  if (ENC[j->codec](SRC(j->codec, j->env), enc_buf, sizeof(enc_buf), &len) != 0) {
    j->st = -1;
    return NULL;
  }
  paint_below(j);
  if (j->op < 0) return NULL;
  if (j->op == 0) {
    j->st = ENC[j->codec](SRC(j->codec, j->env), out_buf, sizeof(out_buf), &len);
  } else {
    itsv_arena av;
    itst_arena at;
    av.base = arena_mem; av.cap = sizeof(arena_mem); av.used = 0;
    at.base = arena_mem; at.cap = sizeof(arena_mem); at.used = 0;
    j->st = DEC[j->codec](enc_buf, len, &value, j->codec < 3 ? (void *)&av : (void *)&at);
  }
  return NULL;
}

static long stack_high_water(stack_job *j) {
  uint8_t *stack = (uint8_t *)malloc(STACK_SIZE);
  pthread_attr_t attr;
  pthread_t th;
  size_t i = 0;
  uintptr_t deepest;
  if (stack == NULL) return -1;
  j->base = stack;
  memset(stack, STACK_PAINT, STACK_SIZE);
  pthread_attr_init(&attr);
  if (pthread_attr_setstack(&attr, stack, STACK_SIZE) != 0 ||
      pthread_create(&th, &attr, stack_run, j) != 0) {
    pthread_attr_destroy(&attr);
    free(stack);
    return -1;
  }
  pthread_join(th, NULL);
  pthread_attr_destroy(&attr);
  while (i < STACK_SIZE && stack[i] == STACK_PAINT) i++;
  deepest = (uintptr_t)stack + i; /* the address, taken while the block is still live */
  free(stack);
  return (long)(j->entry - deepest);
}

/* A certificate whose signer is a pointer back to the signer that holds it: a cyclic value,
 * which a caller can build and no encoder may follow forever. Every encoder must refuse it
 * with the depth bound (status 5) rather than recurse until the stack runs out. */
static int cyclic_encode(int codec, uint8_t *out, size_t cap, size_t *len) {
  if (codec < 3) {
    static itsv_HeaderField hf[8];
    itsv_SecuredMessage m = *V[1];
    if (m.headerFields.n > 8) return -1;
    memcpy(hf, m.headerFields.v, m.headerFields.n * sizeof(hf[0]));
    hf[0].u.signerInfo.u.certificate.signerInfo = &hf[0].u.signerInfo;
    m.headerFields.v = hf;
    return ENC[codec](&m, out, cap, len);
  } else if (codec == 3) {
    itst_SecuredMessage m = *T[1];
    m.headerFields.signerInfo.u.certificate.signerInfo = &m.headerFields.signerInfo;
    return ENC[codec](&m, out, cap, len);
  } else {
    itst_SecuredMessagePer m = *TP[1];
    m.headerFields.signerInfo.u.certificate.signerInfo = &m.headerFields.signerInfo;
    return ENC[codec](&m, out, cap, len);
  }
}

static int codec_index(const char *name) {
  int c;
  for (c = 0; c < N_CODECS; c++) if (!strcmp(name, CODECS[c])) return c;
  return -1;
}

int main(void) {
  static char line[1 << 16];
  static uint8_t buf[1 << 15], out[1 << 15];
  while (fgets(line, sizeof(line), stdin)) {
    char op[16], codec[32], arg[1 << 15];
    if (!strchr(line, '\n') && !feof(stdin)) {  /* longer than the buffer: refused whole */
      int ch;
      while ((ch = getchar()) != EOF && ch != '\n') continue;
      printf("ERR long\n");
      continue;
    }
    if (sscanf(line, "%15s", op) != 1) continue;
    if (!strcmp(op, "enc")) {
      int i, st;
      size_t len = 0, k;
      if (sscanf(line, "%15s %31s %d", op, codec, &i) != 3 || i < 0 || i >= N_ENV) {
        printf("ERR usage\n");
        continue;
      }
      st = encode(codec, i, out, sizeof(out), &len);
      if (st != 0) { printf("ERR %d\n", st); continue; }
      printf("OK ");
      for (k = 0; k < len; k++) printf("%02x", out[k]);
      printf("\n");
    } else if (!strcmp(op, "dec")) {
      size_t n = 0, used = 0, re_len = 0, k;
      int match, st;
      arg[0] = 0;
      if (sscanf(line, "%15s %31s %32767s", op, codec, arg) < 2) { printf("ERR usage\n"); continue; }
      if (strlen(arg) == sizeof(arg) - 1u) { printf("ERR hex\n"); continue; }  /* cut by %s */
      if (!strcmp(arg, "-")) arg[0] = 0;
      if (unhex(arg, buf, sizeof(buf), &n) != 0) { printf("ERR hex\n"); continue; }
      st = decode(codec, buf, n, &match, &used, out, sizeof(out), &re_len);
      if (st < 16) { printf("ERR %d\n", st); continue; }
      if (st != 16) { printf("REENCODE %d\n", st - 16); continue; }
      printf("OK %d %zu ", match, used);
      for (k = 0; k < re_len; k++) printf("%02x", out[k]);
      printf("\n");
    } else if (!strcmp(op, "stack")) {
      stack_job base, j;
      int env = 0, which = 0;
      long used, idle;
      if (sscanf(line, "%15s %31s %d %d", op, codec, &env, &which) != 4 || env < 0 ||
          env >= N_ENV || codec_index(codec) < 0 || which < 0 || which > 1) {
        printf("ERR usage\n");
        continue;
      }
      base.codec = codec_index(codec); base.env = env; base.op = -1; base.st = 0;
      j = base;
      j.op = which;
      idle = stack_high_water(&base);
      used = stack_high_water(&j);
      /* `used` is the depth below the entry frame: the codec's frames plus the call into it,
       * so an upper bound on the codec's own stack. `idle` (the paint's own reach) is printed
       * so a reader can see the bound is not the margin. */
      if (idle < 0 || used < 0 || j.st != 0) printf("ERR %d\n", j.st);
      else printf("OK %ld %ld\n", used, idle);
    } else if (!strcmp(op, "cycle")) {
      int c;
      printf("OK");
      for (c = 0; c < N_CODECS; c++) {
        size_t len = 0;
        printf(" %d", cyclic_encode(c, out, sizeof(out), &len));
      }
      printf("\n");
    } else if (!strcmp(op, "bench")) {
      long rounds = 0, iters = 0;
      if (sscanf(line, "%15s %ld %ld", op, &rounds, &iters) != 3 || rounds < 4 || iters < 1) {
        printf("ERR usage\n");
        continue;
      }
      bench(rounds, iters);
    }
    fflush(stdout);
  }
  return 0;
}
"""


_FUZZ = r"""
/* fuzz_its_codecs.c -- libFuzzer over every generated ITS decoder (bcir/asn1/its_native.py).
 *
 * The first octet picks the codec; the rest is the encoding. Besides memory safety the target
 * checks the canonical-only property: whatever a decoder accepts must re-encode to exactly the
 * octets it was given, or there are two spellings of one value -- an abort, so the fuzzer
 * reports it as a crash. */
#include <stdint.h>
#include <stdlib.h>
#include <string.h>

#include "itsv_codec.h"
#include "itst_codec.h"

static uint8_t arena_mem[1 << 16];
static uint8_t out[1 << 15];

int LLVMFuzzerTestOneInput(const uint8_t *data, size_t size) {
  size_t len = 0;
  int st, re;
  if (size < 1u) return 0;
  {
    unsigned codec = data[0] % 5u;
    const uint8_t *in = data + 1;
    size_t n = size - 1u;
    if (codec < 3u) {
      itsv_SecuredMessage v;
      itsv_arena a;
      a.base = arena_mem; a.cap = sizeof(arena_mem); a.used = 0;
      st = codec == 0u ? itsv_v111_decode_SecuredMessage(in, n, &v, &a)
         : codec == 1u ? itsv_coer_decode_SecuredMessage(in, n, &v, &a)
                       : itsv_uper_decode_SecuredMessage(in, n, &v, &a);
      if (st != 0) return 0;
      re = codec == 0u ? itsv_v111_encode_SecuredMessage(&v, out, sizeof(out), &len)
         : codec == 1u ? itsv_coer_encode_SecuredMessage(&v, out, sizeof(out), &len)
                       : itsv_uper_encode_SecuredMessage(&v, out, sizeof(out), &len);
    } else {
      itst_arena a;
      a.base = arena_mem; a.cap = sizeof(arena_mem); a.used = 0;
      if (codec == 3u) {
        itst_SecuredMessage v;
        if (itst_coer_decode_SecuredMessage(in, n, &v, &a) != 0) return 0;
        re = itst_coer_encode_SecuredMessage(&v, out, sizeof(out), &len);
      } else {
        itst_SecuredMessagePer v;
        if (itst_uper_decode_SecuredMessagePer(in, n, &v, &a) != 0) return 0;
        re = itst_uper_encode_SecuredMessagePer(&v, out, sizeof(out), &len);
      }
      st = 0;
    }
    if (re != 0 || len != n || memcmp(out, in, n) != 0) abort();
  }
  return 0;
}
"""


def fuzz_sources() -> dict:
    """The generated codecs and a libFuzzer target over every decoder."""
    files = {k: v for k, v in sources().items() if k != "its_harness.c"}
    files["fuzz_its_codecs.c"] = _FUZZ
    return files


def seeds() -> list[bytes]:
    """One seed per codec and envelope: the codec's selector octet, then the oracle's octets."""
    want = oracle_octets()
    return [
        bytes([n]) + want[(codec, i)] for n, (codec, _m, _r) in enumerate(CODECS) for i in range(4)
    ]


def build(tmp: str, *, cc: str | None = None, flags=("-O2",)) -> str | None:
    """Compile the harness in `tmp`; the binary's path, or None when no C compiler exists."""
    from ..toolchain import host_c_compiler

    cc = cc or host_c_compiler()
    if cc is None:
        return None
    for name, text in sources().items():
        with open(os.path.join(tmp, name), "w", encoding="utf-8", newline="\n") as f:
            f.write(text)
    out = os.path.join(tmp, "its_harness")
    proc = subprocess.run(
        [
            cc,
            "-std=c11",
            *flags,
            "-Wall",
            "-Wextra",
            "-Werror",
            "-I",
            tmp,
            os.path.join(tmp, "its_harness.c"),
            os.path.join(tmp, "itsv_codec.c"),
            os.path.join(tmp, "itst_codec.c"),
            "-o",
            out,
            "-pthread",
        ],
        capture_output=True,
        text=True,
        timeout=600,
    )
    if proc.returncode != 0:
        raise Asn1Error(f"the ITS harness does not compile: {proc.stderr[-3000:]}")
    return out


def run(binary: str, lines: list[str], timeout: int = 600) -> list[str]:
    proc = subprocess.run(
        [binary], input="\n".join(lines) + "\n", capture_output=True, text=True, timeout=timeout
    )
    if proc.returncode != 0:
        raise Asn1Error(f"the ITS harness failed: {proc.stderr[-2000:]}")
    return proc.stdout.splitlines()


def oracle_octets() -> dict:
    """`{(codec, envelope index): octets}` from the Python rails -- what every generated
    encoder must write."""
    from . import its_security as its
    from .oer import encode_oer
    from .per import encode_per

    t, m = its.transcription_type(), its.tmsao_type()
    out = {}
    for i, value in enumerate(its.envelopes().values()):
        tv = its.to_tmsao(value)
        out[("v111", i)] = its.encode_binary(value)
        out[("coer", i)] = encode_oer(t, value)
        out[("uper", i)] = encode_per(t, value)
        out[("tmsao-coer", i)] = encode_oer(m, tv)
        out[("tmsao-uper", i)] = encode_per(its.tmsao_type("SecuredMessagePer"), tv)
    return out


@dataclass(frozen=True)
class Timing:
    codec: str
    envelope: int
    op: str  # encode / decode / floor
    octets: int
    q1_ns: float
    median_ns: float
    q3_ns: float


def bench(binary: str, *, rounds: int = 64, iters: int = 2000) -> list[Timing]:
    out = []
    for line in run(binary, [f"bench {rounds} {iters}"], timeout=1800):
        parts = line.split()
        if parts and parts[0] == "ERR":
            raise Asn1Error(f"the ITS bench refused: {line}")
        if parts and parts[0] == "time":
            out.append(
                Timing(
                    parts[1],
                    int(parts[2]),
                    parts[3],
                    int(parts[4]),
                    float(parts[5]),
                    float(parts[6]),
                    float(parts[7]),
                )
            )
    return out


@dataclass(frozen=True)
class Memory:
    """What one codec takes beyond its input and output buffers, on one envelope."""

    codec: str
    envelope: int
    heap_octets: int  # 0 by construction; `allocator_symbols` is the proof
    arena_octets: int  # decode only: the caller's arena, exactly
    encode_stack: int  # octets of stack the encode reached, measured
    decode_stack: int


#: Symbols that would mean a generated codec allocates.
ALLOCATORS = frozenset(
    {
        "malloc",
        "calloc",
        "realloc",
        "free",
        "aligned_alloc",
        "posix_memalign",
        "memalign",
        "valloc",
        "pvalloc",
    }
)


def allocator_symbols(tmp: str, cc: str | None = None) -> dict:
    """`{codec file: allocator symbols it references}` -- empty sets, or the claim of a
    heap-free codec is false. Read from the objects with `nm -u`; None when there is no nm."""
    from ..toolchain import host_c_compiler

    nm = shutil.which("nm") or shutil.which("llvm-nm")
    cc = cc or host_c_compiler()
    if nm is None or cc is None:
        return {}
    out = {}
    for name in ("itsv_codec.c", "itst_codec.c"):
        obj = os.path.join(tmp, name + ".o")
        subprocess.run(
            [cc, "-std=c11", "-O2", "-c", "-I", tmp, os.path.join(tmp, name), "-o", obj],
            check=True,
            capture_output=True,
            timeout=300,
        )
        syms = subprocess.run([nm, "-u", obj], capture_output=True, text=True, check=True).stdout
        out[name] = {line.split()[-1] for line in syms.splitlines() if line.split()} & ALLOCATORS
    return out


def memory(binary: str) -> list[Memory]:
    """Arena and stack, per codec and envelope, measured in the harness."""
    from . import its_security as its

    want = oracle_octets()
    lines = []
    keys = []
    for codec, _model, _rule in CODECS:
        for i in range(len(its.PROFILES)):
            keys.append((codec, i))
            lines += [
                f"dec {codec} {want[(codec, i)].hex()}",
                f"stack {codec} {i} 0",
                f"stack {codec} {i} 1",
            ]
    got = run(binary, lines)
    out = []
    for n, (codec, i) in enumerate(keys):
        dec, enc_stack, dec_stack = got[3 * n : 3 * n + 3]
        if not (dec.startswith("OK") and enc_stack.startswith("OK") and dec_stack.startswith("OK")):
            raise Asn1Error(f"memory: {codec} envelope {i}: {dec} / {enc_stack} / {dec_stack}")
        out.append(
            Memory(
                codec,
                i,
                0,
                int(dec.split()[2]),
                int(enc_stack.split()[1]),
                int(dec_stack.split()[1]),
            )
        )
    return out


def native_available() -> bool:
    from ..toolchain import host_c_compiler

    return host_c_compiler() is not None and shutil.which("true") is not None


__all__ = [
    "ALLOCATORS",
    "CODECS",
    "STATUS",
    "Memory",
    "Timing",
    "allocator_symbols",
    "bench",
    "build",
    "fuzz_sources",
    "memory",
    "native_available",
    "oracle_octets",
    "run",
    "seeds",
    "sources",
]


def _main(argv: list[str] | None = None) -> int:  # pragma: no cover - a developer convenience
    """`python -m bcir.asn1.its_native [DIR [CC]]`: build the harness in DIR (a new directory
    when omitted, kept so the binary can be run again) and print the study's timing and memory
    tables for this host."""
    import sys

    args = sys.argv[1:] if argv is None else argv
    tmp = args[0] if args else tempfile.mkdtemp(prefix="bcir-its-")
    os.makedirs(tmp, exist_ok=True)
    binary = build(tmp, cc=args[1] if len(args) > 1 else None)
    if binary is None:
        print("no C compiler on this host")
        return 1
    print(binary)
    rows = {(t.codec, t.envelope, t.op): t for t in bench(binary)}
    print("codec        per envelope p1 / p1cert / p2 / p3: octets, encode / decode ns (median)")
    for codec, _model, _rule in CODECS:
        cells = []
        for env in range(4):
            enc, dec = rows[(codec, env, "encode")], rows[(codec, env, "decode")]
            cells.append(f"{enc.octets:3} {enc.median_ns:6.1f} / {dec.median_ns:6.1f}")
        print(f"{codec:12} " + "   ".join(cells))
    print("codec        envelope: heap, arena octets, encode / decode stack high-water")
    for m in memory(binary):
        print(
            f"{m.codec:12} {m.envelope}: {m.heap_octets}, {m.arena_octets}, "
            f"{m.encode_stack} / {m.decode_stack}"
        )
    return 0


if __name__ == "__main__":  # pragma: no cover
    raise SystemExit(_main())
