# The source manifest reader: runtime/manifest.json is the ONE list of what the C and C++ rails
# are made of -- libraries by memory class, tools, harnesses, fuzz targets, the C++ seam and the
# freestanding checks -- and this reads it into variables the CMakeLists under runtime/ turn into
# targets.
#
# Why a manifest and not CMake lists: three Python harnesses and two shell gates used to carry
# their own copies of these source sets (the #719 trap: a gate and a harness that link different
# sources), and `bcir/tests/test_build_manifest.py` now holds every one of them to this file.
# CMake reads the JSON itself (string(JSON ...), CMake >= 3.19) so a configure needs no Python.
#
# After bcir_manifest_load(path):
#   BCIR_MANIFEST_<kind>            lists of unit names, for each kind in BCIR_MANIFEST_KINDS
#   BCIR_<kind>_<name>_SOURCES      the unit's sources (basenames under runtime/c, or runtime/cpp
#                                   for the seam_* kinds)
#   BCIR_<kind>_<name>_LIBRARIES    the manifest libraries it links
#   BCIR_<kind>_<name>_LINK         system libraries it links (m, pthread)
#   BCIR_<kind>_<name>_OPTIONS      GNU-style compile options the gates pass for that unit
#   BCIR_<kind>_<name>_CLASS        libraries only: freestanding_core / hosted_tool / driver_adapter
#   BCIR_<kind>_<name>_MAX_LEN      fuzzers only: libFuzzer's -max_len, or empty
#   BCIR_MANIFEST_FREESTANDING      the sources compiled -ffreestanding -nostdlib at C11 and C23
#   BCIR_MANIFEST_sections          the gate sections that run as scripts over built harnesses
#   BCIR_sections_<name>_SCRIPT     the script (a path under the source tree)
#   BCIR_sections_<name>_HARNESSES  the binaries it takes (harnesses or variants), in argument order
#   BCIR_MANIFEST_variants          harnesses rebuilt with their closure: extra options, one
#                                   mutation, another C standard or a sanitizer
#   BCIR_variants_<name>_OF         the harness a variant rebuilds
#   BCIR_variants_<name>_OPTIONS    options appended after the build's own (-O0, -O3)
#   BCIR_variants_<name>_MUTATION_FILE  the one source a mutant edits (the edit itself is applied by
#                                   tools/build/mutate.py at build time; CMake never spells it)
#   BCIR_variants_<name>_STANDARD   the C standard it builds in when not the harness's C23 (11, 17)
#   BCIR_variants_<name>_SANITIZER  the sanitizer it builds with (thread), empty when none
#   BCIR_MANIFEST_kernels           programs the Python oracle emits (bcir.lower.c_kernel), each with a
#                                   driver appended: tools/build/emit_kernel.py writes the unit
#   BCIR_kernels_<name>_MAIN        the driver (a basename under runtime/c/kernels)
#   BCIR_kernels_<name>_LINK        system libraries it links (m, pthread)
include_guard(GLOBAL)

set(BCIR_MANIFEST_KINDS libraries tools harnesses fuzzers seam_libraries seam_tests)

# A JSON array under `key` of `json` as a CMake list in `outvar` (empty when the key is absent).
function(_bcir_json_list json key outvar)
  string(JSON _n ERROR_VARIABLE _err LENGTH "${json}" ${key})
  if(_err OR _n EQUAL 0)
    set(${outvar} "" PARENT_SCOPE)
    return()
  endif()
  set(_items "")
  math(EXPR _last "${_n} - 1")
  foreach(_i RANGE 0 ${_last})
    string(JSON _item GET "${json}" ${key} ${_i})
    list(APPEND _items "${_item}")
  endforeach()
  set(${outvar} "${_items}" PARENT_SCOPE)
endfunction()

# A JSON string under `key` of `json` in `outvar` (empty when absent).
function(_bcir_json_string json key outvar)
  string(JSON _value ERROR_VARIABLE _err GET "${json}" ${key})
  if(_err)
    set(${outvar} "" PARENT_SCOPE)
  else()
    set(${outvar} "${_value}" PARENT_SCOPE)
  endif()
endfunction()

function(bcir_manifest_load path)
  # The manifest is the build's input: an edit to it re-runs the configure, as an edit to a
  # CMakeLists.txt does (without this, `cmake --build` kept building the old unit lists).
  set_property(DIRECTORY "${CMAKE_SOURCE_DIR}" APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${path}")
  file(READ "${path}" _json)
  string(JSON _schema ERROR_VARIABLE _err GET "${_json}" schema)
  if(_err OR NOT _schema STREQUAL "bcir-build-manifest.v1")
    message(FATAL_ERROR "BCIR: ${path} is not a bcir-build-manifest.v1 (${_err})")
  endif()
  set(_total 0)
  foreach(_kind IN LISTS BCIR_MANIFEST_KINDS)
    string(JSON _n ERROR_VARIABLE _err LENGTH "${_json}" ${_kind})
    if(_err)
      message(FATAL_ERROR "BCIR: ${path} has no '${_kind}' object (${_err})")
    endif()
    set(_names "")
    if(_n GREATER 0)
      math(EXPR _last "${_n} - 1")
      foreach(_i RANGE 0 ${_last})
        string(JSON _name MEMBER "${_json}" ${_kind} ${_i})
        list(APPEND _names "${_name}")
        string(JSON _unit GET "${_json}" ${_kind} ${_name})
        _bcir_json_list("${_unit}" sources _sources)
        _bcir_json_list("${_unit}" libraries _libs)
        _bcir_json_list("${_unit}" link _link)
        _bcir_json_list("${_unit}" options _options)
        _bcir_json_string("${_unit}" class _class)
        _bcir_json_string("${_unit}" max_len _max_len)
        if(NOT _sources)
          message(FATAL_ERROR "BCIR: manifest unit ${_kind}/${_name} lists no sources")
        endif()
        set(BCIR_${_kind}_${_name}_SOURCES "${_sources}" PARENT_SCOPE)
        set(BCIR_${_kind}_${_name}_LIBRARIES "${_libs}" PARENT_SCOPE)
        set(BCIR_${_kind}_${_name}_LINK "${_link}" PARENT_SCOPE)
        set(BCIR_${_kind}_${_name}_OPTIONS "${_options}" PARENT_SCOPE)
        set(BCIR_${_kind}_${_name}_CLASS "${_class}" PARENT_SCOPE)
        set(BCIR_${_kind}_${_name}_MAX_LEN "${_max_len}" PARENT_SCOPE)
      endforeach()
    endif()
    set(BCIR_MANIFEST_${_kind} "${_names}" PARENT_SCOPE)
    math(EXPR _total "${_total} + ${_n}")
  endforeach()
  # sections: {name: {script, harnesses}} -- the gate sections that moved into tools/c/sections/.
  set(_section_names "")
  string(JSON _nsec ERROR_VARIABLE _err LENGTH "${_json}" sections)
  if(NOT _err AND _nsec GREATER 0)
    math(EXPR _last "${_nsec} - 1")
    foreach(_i RANGE 0 ${_last})
      string(JSON _name MEMBER "${_json}" sections ${_i})
      string(JSON _unit GET "${_json}" sections ${_name})
      _bcir_json_string("${_unit}" script _script)
      _bcir_json_list("${_unit}" harnesses _harnesses)
      if(NOT _script OR NOT _harnesses)
        message(FATAL_ERROR "BCIR: manifest section ${_name} needs a script and at least one harness")
      endif()
      list(APPEND _section_names "${_name}")
      set(BCIR_sections_${_name}_SCRIPT "${_script}" PARENT_SCOPE)
      set(BCIR_sections_${_name}_HARNESSES "${_harnesses}" PARENT_SCOPE)
    endforeach()
  endif()
  set(BCIR_MANIFEST_sections "${_section_names}" PARENT_SCOPE)
  # variants: {name: {of, options?, mutation?: {file, find, replace}, standard?, sanitizer?}}
  set(_variant_names "")
  string(JSON _nvar ERROR_VARIABLE _err LENGTH "${_json}" variants)
  if(NOT _err AND _nvar GREATER 0)
    math(EXPR _last "${_nvar} - 1")
    foreach(_i RANGE 0 ${_last})
      string(JSON _name MEMBER "${_json}" variants ${_i})
      string(JSON _unit GET "${_json}" variants ${_name})
      _bcir_json_string("${_unit}" of _of)
      _bcir_json_list("${_unit}" options _vopts)
      string(JSON _mfile ERROR_VARIABLE _merr GET "${_unit}" mutation file)
      if(_merr)
        set(_mfile "")
      endif()
      string(JSON _std ERROR_VARIABLE _serr GET "${_unit}" standard)
      if(_serr)
        set(_std "")
      elseif(NOT _std MATCHES "^(11|17)$")
        message(FATAL_ERROR "BCIR: manifest variant ${_name} builds in C standard '${_std}' (11 or 17; the harness's own is 23)")
      endif()
      _bcir_json_string("${_unit}" sanitizer _san)
      if(_san AND NOT _san STREQUAL "thread")
        message(FATAL_ERROR "BCIR: manifest variant ${_name} names sanitizer '${_san}' (known: thread)")
      endif()
      if(NOT _of OR (NOT _vopts AND NOT _mfile AND NOT _std AND NOT _san))
        message(FATAL_ERROR "BCIR: manifest variant ${_name} needs `of` and options, a mutation, a standard or a sanitizer")
      endif()
      list(APPEND _variant_names "${_name}")
      set(BCIR_variants_${_name}_OF "${_of}" PARENT_SCOPE)
      set(BCIR_variants_${_name}_OPTIONS "${_vopts}" PARENT_SCOPE)
      set(BCIR_variants_${_name}_MUTATION_FILE "${_mfile}" PARENT_SCOPE)
      set(BCIR_variants_${_name}_STANDARD "${_std}" PARENT_SCOPE)
      set(BCIR_variants_${_name}_SANITIZER "${_san}" PARENT_SCOPE)
    endforeach()
  endif()
  set(BCIR_MANIFEST_variants "${_variant_names}" PARENT_SCOPE)
  # kernels: {name: {emit, args, main, link?}} -- C the Python oracle emits with a driver appended.
  # The emitter and its arguments are tools/build/emit_kernel.py's to read; the build needs the
  # driver (a dependency of the unit) and the system libraries.
  set(_kernel_names "")
  string(JSON _nker ERROR_VARIABLE _err LENGTH "${_json}" kernels)
  if(NOT _err AND _nker GREATER 0)
    math(EXPR _last "${_nker} - 1")
    foreach(_i RANGE 0 ${_last})
      string(JSON _name MEMBER "${_json}" kernels ${_i})
      string(JSON _unit GET "${_json}" kernels ${_name})
      _bcir_json_string("${_unit}" main _kmain)
      _bcir_json_list("${_unit}" link _klink)
      if(NOT _kmain)
        message(FATAL_ERROR "BCIR: manifest kernel ${_name} names no driver (main)")
      endif()
      list(APPEND _kernel_names "${_name}")
      set(BCIR_kernels_${_name}_MAIN "${_kmain}" PARENT_SCOPE)
      set(BCIR_kernels_${_name}_LINK "${_klink}" PARENT_SCOPE)
    endforeach()
  endif()
  set(BCIR_MANIFEST_kernels "${_kernel_names}" PARENT_SCOPE)
  _bcir_json_list("${_json}" freestanding_checks _free)
  if(NOT _free)
    message(FATAL_ERROR "BCIR: ${path} lists no freestanding_checks (the freestanding core is unproven)")
  endif()
  set(BCIR_MANIFEST_FREESTANDING "${_free}" PARENT_SCOPE)
  list(LENGTH _free _nfree)
  list(LENGTH _section_names _nsections)
  list(LENGTH _variant_names _nvariants)
  list(LENGTH _kernel_names _nkernels)
  message(STATUS "BCIR manifest: ${_total} units, ${_nvariants} variants, ${_nkernels} kernels, ${_nfree} freestanding checks, ${_nsections} sections (${path})")
endfunction()

# The manifest's basenames as paths under runtime/c (bcir_manifest_paths) or runtime/cpp
# (bcir_manifest_cpp_paths).
function(bcir_manifest_paths outvar)
  set(_paths "")
  foreach(_s IN LISTS ARGN)
    list(APPEND _paths "${BCIR_C_DIR}/${_s}")
  endforeach()
  set(${outvar} "${_paths}" PARENT_SCOPE)
endfunction()

function(bcir_manifest_cpp_paths outvar)
  set(_paths "")
  foreach(_s IN LISTS ARGN)
    list(APPEND _paths "${BCIR_CPP_DIR}/${_s}")
  endforeach()
  set(${outvar} "${_paths}" PARENT_SCOPE)
endfunction()

# The transitive closure of manifest libraries: every source, system library and option the
# named libraries and their dependencies carry, each once, dependents first. A fuzz target
# compiles this closure into itself (the gates' one-command build) so libFuzzer's coverage and
# the sanitizers instrument the code under test, not only the harness.
function(bcir_manifest_closure outvar)
  set(_todo ${ARGN})
  set(_seen "")
  set(_srcs "")
  set(_link "")
  set(_opts "")
  while(_todo)
    list(POP_FRONT _todo _lib)
    if(_lib IN_LIST _seen)
      continue()
    endif()
    if(NOT DEFINED BCIR_libraries_${_lib}_SOURCES)
      message(FATAL_ERROR "BCIR: manifest names an unknown library '${_lib}'")
    endif()
    list(APPEND _seen "${_lib}")
    list(APPEND _srcs ${BCIR_libraries_${_lib}_SOURCES})
    list(APPEND _link ${BCIR_libraries_${_lib}_LINK})
    list(APPEND _opts ${BCIR_libraries_${_lib}_OPTIONS})
    list(APPEND _todo ${BCIR_libraries_${_lib}_LIBRARIES})
  endwhile()
  list(REMOVE_DUPLICATES _link)
  list(REMOVE_DUPLICATES _opts)
  set(${outvar} "${_srcs}" PARENT_SCOPE)
  set(${outvar}_LINK "${_link}" PARENT_SCOPE)
  set(${outvar}_OPTIONS "${_opts}" PARENT_SCOPE)
endfunction()

# Link a target against manifest libraries and the manifest's system-library names.
function(bcir_manifest_link target scope libraries link)
  foreach(_lib IN LISTS libraries)
    target_link_libraries(${target} ${scope} ${_lib})
  endforeach()
  foreach(_sys IN LISTS link)
    if(_sys STREQUAL "pthread")
      if(TARGET Threads::Threads)
        target_link_libraries(${target} ${scope} Threads::Threads)
      elseif(NOT MSVC)
        target_link_libraries(${target} ${scope} pthread)
      endif()
    elseif(_sys STREQUAL "m")
      if(NOT MSVC)
        target_link_libraries(${target} ${scope} m)
      endif()
    else()
      message(FATAL_ERROR "BCIR: manifest link entry '${_sys}' on ${target} is not one of: m, pthread")
    endif()
  endforeach()
endfunction()

# The manifest's per-unit compile options: GNU spellings, applied on GCC and Clang; an entry
# prefixed `gcc:` or `clang:` applies to that compiler only (a warning family one compiler lacks
# is an unknown-option error under -Werror on the other). MSVC takes none of them.
function(bcir_manifest_options target options)
  if(NOT options OR NOT BCIR_GNU_LIKE)
    return()
  endif()
  set(_apply "")
  foreach(_opt IN LISTS options)
    if(_opt MATCHES "^gcc:(.*)$")
      if(CMAKE_C_COMPILER_ID STREQUAL "GNU")
        list(APPEND _apply "${CMAKE_MATCH_1}")
      endif()
    elseif(_opt MATCHES "^clang:(.*)$")
      if(CMAKE_C_COMPILER_ID MATCHES "Clang")
        list(APPEND _apply "${CMAKE_MATCH_1}")
      endif()
    else()
      list(APPEND _apply "${_opt}")
    endif()
  endforeach()
  if(_apply)
    target_compile_options(${target} PRIVATE ${_apply})
  endif()
endfunction()
